"""Tests for scripts/modem_profile.py (modem profiles, one-command swap).

The module is imported the same way deploy/install.py is in
test_install_noninteractive.py — module level only defines constants,
renderers and functions; main() is guarded by ``__main__``.

All state paths are redirected into tmp_path via environment variables
and every shell command goes through the module's single run() hook,
which the ``st`` fixture stubs. No test touches real udev, Asterisk,
systemd, or serial ports.

Covered:
- validate_profile / render_profile round-trip + invalid-profile rejects
- render_dongle_conf (audio/data + app-level constants)
- render_udev_rules (PID + interface-number keying; refuse when missing;
  ID_MM_DEVICE_IGNORE on the USB device AND every port of its subtree —
  ModemManager isolation, see the EBUSY notes in the script)
- patch_yaml_field (surgical — every other line byte-identical)
- backup()
- apply_artifacts (render + backups, idempotency, legacy 99-dongle.rules
  retirement only for the same USB PID)
- _switch / use (verified gate, surgical yaml update, restart policy,
  idempotent no-op, rollback + exit 1 on failed verification)
- probe (AT port detection via stubbed AT answers, USBCFG, --commit
  writes an unverified profile with dongle_if<iface-as-int> symlinks)
- capture (_capture_from_live from stubbed udev state)
- list (active marker, empty dir)
- status (MATCH/MISMATCH marking, ModemManager adoption warning)
"""

from __future__ import annotations

import os
import re
import sys
import types
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "scripts"))
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import modem_profile  # noqa: E402


# ---------------------------------------------------------------------------
# Fixtures / stubs
# ---------------------------------------------------------------------------

def _hprofile(**kw) -> dict:
    """A Huawei-shaped profile (the reference live state)."""
    p = {
        "name": "huawei-e161",
        "modem_model": "Huawei E161/E169/E620/E800 HSDPA Modem",
        "vid_pid": "12d1:1001",
        "dongle_name": "gsm",
        "audio_device": "/dev/dongle_if1",
        "data_device": "/dev/dongle_if2",
        "sim_phone": "+79000000000",
        "udev": [
            {"iface": "00", "symlink": "dongle_if0"},
            {"iface": "01", "symlink": "dongle_if1"},
            {"iface": "02", "symlink": "dongle_if2"},
        ],
        "verified": True,
        "notes": "captured from live state",
    }
    p.update(kw)
    return p


LIVE_YAML = """\
# SimBridge — generated by install.py
node:
  role: gsm
  id: 3p14-aaa
telegram:
  master_username: "user"
  session_path: /var/lib/simbridge/sim_session
  acl_file: /etc/simbridge/acl.conf
  api_id_env: SIMBRIDGE_TG_API_ID
  api_hash_env: SIMBRIDGE_TG_API_HASH
agent:
  listen: "100.124.155.106:8090"
  token_env: SIMBRIDGE_AGENT_TOKEN
  userbot_url: http://100.95.195.40:8088
asterisk:
  ari_url: http://127.0.0.1:8088/ari
  dongle: gsm
  ring_wait_seconds: 18
  max_record_seconds: 90
sim:
  phone: "+79000000000"
  modem_model: "Bus 003 Device 002: ID 12d1:1001 Huawei"
voice:
  srtp: false
paths:
  blacklist: /etc/simbridge/blacklist.txt
"""


def _fake_run_output(cmd: str, root: Path):
    """Canned outputs for the stubbed run(); rc 0 unless noted."""
    if "udevadm control" in cmd or "systemctl restart" in cmd:
        return types.SimpleNamespace(returncode=0, stdout="", stderr="")
    if cmd.startswith("ls -1 /dev/dongle_if*"):
        f = root / "stub_dongle_ifs"
        out = f.read_text() if f.exists() else ""
        return types.SimpleNamespace(returncode=0, stdout=out, stderr="")
    if "udevadm info -q all -n" in cmd:
        dev = re.search(r"-n (\S+)", cmd).group(1).strip("'\"")
        f = root / f"stub_meta_{Path(dev).name}"
        out = f.read_text() if f.exists() else ""
        return types.SimpleNamespace(returncode=0, stdout=out, stderr="")
    if cmd.startswith("lsusb"):
        f = root / "stub_lsusb"
        out = f.read_text() if f.exists() else ""
        return types.SimpleNamespace(returncode=0, stdout=out, stderr="")
    if "dongle show devices" in cmd:
        f = root / "stub_dongle_show"
        out = f.read_text() if f.exists() else "Error: unknown command"
        rc = 0 if f.exists() else 1
        return types.SimpleNamespace(returncode=rc, stdout=out,
                                     stderr="" if f.exists() else out)
    if "is-active simbridge-agent" in cmd:
        return types.SimpleNamespace(returncode=0, stdout="active\n",
                                     stderr="")
    if cmd.startswith("systemctl is-active ModemManager"):
        f = root / "stub_mm_active"
        out = f.read_text().strip() if f.exists() else ""
        return types.SimpleNamespace(returncode=0, stdout=out + "\n",
                                     stderr="")
    if cmd.startswith("mmcli -L"):
        f = root / "stub_mmcli"
        out = f.read_text() if f.exists() else ""
        return types.SimpleNamespace(returncode=0, stdout=out, stderr="")
    if cmd.startswith("ls -1 /dev/ttyUSB*") or cmd.startswith(
            "ls -1 /dev/ttyACM*"):
        f = root / "stub_tty_devs"
        out = f.read_text() if f.exists() else ""
        return types.SimpleNamespace(returncode=0, stdout=out, stderr="")
    # generator invocation and everything else: success, silent
    return types.SimpleNamespace(returncode=0, stdout="", stderr="")


@pytest.fixture
def st(tmp_path, monkeypatch):
    """Env-redirected state paths + run()/sleep stubs in a temp dir."""
    root = tmp_path / "live"
    root.mkdir()
    env = {
        "SIMBRIDGE_PROFILE_DIR": str(root / "profiles"),
        "SIMBRIDGE_ACTIVE_MODEM": str(root / "active_modem"),
        "SIMBRIDGE_DONGLE_CONF": str(root / "dongle.conf"),
        "SIMBRIDGE_UDEV_RULE": str(root / "92-dongle.rules"),
        "SIMBRIDGE_UDEV_RULE_LEGACY": str(root / "99-dongle.rules"),
        "SIMBRIDGE_CONFIG": str(root / "simbridge.yaml"),
        "SIMBRIDGE_ASTERISK_GLOBALS": str(root / "asterisk-globals.conf"),
    }
    for k, v in env.items():
        monkeypatch.setenv(k, v)
    calls: list = []

    def fake_run(cmd, timeout=30):
        calls.append(cmd)
        return _fake_run_output(cmd, root)

    monkeypatch.setattr(modem_profile, "run", fake_run)
    monkeypatch.setattr(modem_profile.time, "sleep",
                        lambda *_a, **_k: None)
    ns = types.SimpleNamespace(root=root, calls=calls, env=env)
    ns.yaml = lambda: (root / "simbridge.yaml").read_text()
    return ns


def _write_live_yaml(st, text: str = LIVE_YAML) -> None:
    (st.root / "simbridge.yaml").write_text(text)


def _stub_udev_dev(st, dev: str, iface: str, vid: str, pid: str,
                   model: str = "TEST-MODEM") -> None:
    (st.root / f"stub_meta_{Path(dev).name}").write_text(
        f"ID_VENDOR_ID={vid}\nID_MODEL_ID={pid}\n"
        f"ID_USB_INTERFACE_NUM={iface}\nID_MODEL={model}\n"
        "DEVPATH=/devices/pci0000:00/0000:00:14.0/usb1/1-1\n")


# ---------------------------------------------------------------------------
# Profile validation + serialization
# ---------------------------------------------------------------------------

class TestProfileSchema:
    def test_render_load_roundtrip(self, st):
        p = _hprofile()
        modem_profile.write_profile(p)
        loaded = modem_profile.load_profile(
            st.root / "profiles" / "huawei-e161.yaml")
        assert loaded == p

    def test_write_rejects_invalid_name(self, st):
        with pytest.raises(modem_profile.ProfileError):
            modem_profile.profile_path("Huawei E161")

    @pytest.mark.parametrize("mutate,match", [
        (lambda p: p.pop("dongle_name"), "dongle_name"),
        (lambda p: p.update(vid_pid="12d1"), "vid_pid"),
        (lambda p: p.update(name="Bad Name"), "name"),
        (lambda p: p.update(verified="yes"), "verified"),
        (lambda p: p.update(udev=[{"iface": "1", "symlink": "x"}]),
         "iface"),
        (lambda p: p.update(udev="nope"), "udev"),
    ])
    def test_validate_rejects(self, st, mutate, match):
        p = _hprofile()
        mutate(p)
        errs = modem_profile.validate_profile(p)
        assert any(match in e for e in errs), errs

    def test_valid_profile_no_errors(self, st):
        assert modem_profile.validate_profile(_hprofile()) == []


# ---------------------------------------------------------------------------
# Renderers
# ---------------------------------------------------------------------------

class TestRenderDongleConf:
    def test_modem_fields_from_profile(self, st):
        text = modem_profile.render_dongle_conf(_hprofile())
        assert "[gsm]" in text
        assert "audio = /dev/dongle_if1" in text
        assert "data = /dev/dongle_if2" in text

    def test_app_constants_preserved(self, st):
        text = modem_profile.render_dongle_conf(_hprofile())
        assert "interval=15" in text
        assert "context = incoming-mobile" in text
        assert "group = 1" in text
        assert "smsaspdu = yes" in text
        assert "autodeletesms = yes" in text

    def test_different_channel_and_devices(self, st):
        p = _hprofile(dongle_name="modem2",
                      audio_device="/dev/ttyUSB1",
                      data_device="/dev/ttyUSB2")
        text = modem_profile.render_dongle_conf(p)
        assert "[modem2]" in text
        assert "audio = /dev/ttyUSB1" in text
        assert "data = /dev/ttyUSB2" in text


class TestRenderUdevRules:
    def test_three_rules_keyed_by_pid_and_iface(self, st):
        text = modem_profile.render_udev_rules(_hprofile())
        tty_rules = [l for l in text.splitlines()
                     if l.startswith('SUBSYSTEM=="tty"')]
        assert len(tty_rules) == 3
        assert all('ENV{ID_MODEL_ID}=="1001"' in r for r in tty_rules)
        assert 'ENV{ID_USB_INTERFACE_NUM}=="01", SYMLINK+="dongle_if1"' \
            in text
        assert 'OWNER="asterisk", GROUP="dialout", MODE="0660"' in text

    def test_mm_ignore_rules_on_device_and_subtree(self, st):
        # Tag on the USB composite (ATTR = own attributes) AND on every
        # device in its subtree (ATTRS = ancestor attributes) — on
        # RHEL9's MM 1.20.2 the composite's properties were not visible
        # to the filter, the ports' own properties were (EBUSY incident).
        text = modem_profile.render_udev_rules(_hprofile())
        lines = text.splitlines()
        assert 'SUBSYSTEM=="usb", ATTR{idVendor}=="12d1", ' \
            'ATTR{idProduct}=="1001", ENV{ID_MM_DEVICE_IGNORE}="1"' in lines
        assert 'ATTRS{idVendor}=="12d1", ATTRS{idProduct}=="1001", ' \
            'ENV{ID_MM_DEVICE_IGNORE}="1"' in lines
        assert len([l for l in lines if "ID_MM_DEVICE_IGNORE" in l]) == 2

    def test_no_mm_rules_without_vid(self, st):
        # pid alone (malformed vid_pid ":1001") still renders the tty
        # symlink rules, but no MM ignore rules can be keyed.
        text = modem_profile.render_udev_rules(_hprofile(vid_pid=":1001"))
        assert "ID_MM_DEVICE_IGNORE" not in text
        assert text.count('SUBSYSTEM=="tty"') == 3

    def test_refuse_without_vid_pid(self, st):
        with pytest.raises(modem_profile.ProfileError):
            modem_profile.render_udev_rules(_hprofile(vid_pid=""))

    def test_refuse_without_udev_map(self, st):
        with pytest.raises(modem_profile.ProfileError):
            modem_profile.render_udev_rules(_hprofile(udev=[]))


# ---------------------------------------------------------------------------
# Surgical yaml patch + backup
# ---------------------------------------------------------------------------

class TestPatchYaml:
    def test_surgical_update_other_lines_identical(self, st):
        new = modem_profile.patch_yaml_field(LIVE_YAML, "asterisk", "dongle",
                                             "gsm", quote=False)
        new = modem_profile.patch_yaml_field(new, "sim", "modem_model",
                                             "new model: with colon")
        # every line that was not the target is byte-identical
        skip_old = {"  dongle: gsm", '  modem_model: "Bus 003 Device 002: '
                                     'ID 12d1:1001 Huawei"'}
        skip_new = {"  dongle: gsm", '  modem_model: "new model: with colon"'}
        old_lines = [l for l in LIVE_YAML.splitlines() if l not in skip_old]
        new_lines = [l for l in new.splitlines() if l not in skip_new]
        assert old_lines == new_lines
        assert "  dongle: gsm\n" in new
        assert '  modem_model: "new model: with colon"\n' in new
        # untouched values survive
        assert "  ring_wait_seconds: 18" in new
        assert '  phone: "+79000000000"' in new

    def test_missing_section_raises(self, st):
        with pytest.raises(modem_profile.ProfileError):
            modem_profile.patch_yaml_field(LIVE_YAML, "nonexistent", "k", "v")

    def test_missing_key_raises(self, st):
        with pytest.raises(modem_profile.ProfileError):
            modem_profile.patch_yaml_field(LIVE_YAML, "asterisk",
                                           "not_a_key", "v")

    def test_yaml_field_reader(self, st):
        assert modem_profile._yaml_field(LIVE_YAML, "asterisk", "dongle") \
            == "gsm"
        assert modem_profile._yaml_field(LIVE_YAML, "sim", "phone") \
            == "+79000000000"
        assert modem_profile._yaml_field(LIVE_YAML, "sim", "absent") == ""


class TestBackup:
    def test_backup_copies_bytes_and_names(self, st):
        f = st.root / "x.conf"
        f.write_text("data")
        bak = modem_profile.backup(f)
        assert bak
        assert Path(bak).name.startswith("x.conf.bak-")
        assert Path(bak).read_text() == "data"

    def test_backup_missing_returns_empty(self, st):
        assert modem_profile.backup(st.root / "missing") == ""


# ---------------------------------------------------------------------------
# apply_artifacts
# ---------------------------------------------------------------------------

class TestApplyArtifacts:
    def test_renders_and_backs_up(self, st):
        (st.root / "dongle.conf").write_text("old")
        (st.root / "92-dongle.rules").write_text("old")
        _write_live_yaml(st)
        (st.root / "active_modem").write_text("oldname")
        res = modem_profile.apply_artifacts(_hprofile())
        udev = (st.root / "92-dongle.rules").read_text()
        assert 'ENV{ID_MODEL_ID}=="1001"' in udev
        assert "audio = /dev/dongle_if1" in \
            (st.root / "dongle.conf").read_text()
        # 4 artifacts backed up (udev, dongle.conf, yaml, active pointer)
        assert len(res["backups"]) == 4
        assert any("92-dongle.rules.bak-" in b for b in res["backups"])
        assert any("dongle.conf.bak-" in b for b in res["backups"])
        assert any("simbridge.yaml.bak-" in b for b in res["backups"])
        assert any("active_modem.bak-" in b for b in res["backups"])
        # udev was reloaded (tty + usb-scoped trigger: the usb change
        # event carries the ID_MM_DEVICE_IGNORE tag to ModemManager)
        assert any("udevadm trigger --subsystem-match=tty "
                   "--subsystem-match=usb" in c for c in st.calls)

    def test_idempotent_second_call_no_write_no_reload(self, st):
        p = _hprofile()
        modem_profile.apply_artifacts(p)
        u1 = (st.root / "92-dongle.rules").read_bytes()
        d1 = (st.root / "dongle.conf").read_bytes()
        reloads = len([c for c in st.calls if "udevadm control" in c])
        res = modem_profile.apply_artifacts(p)
        assert res["udev"] is None
        assert len([c for c in st.calls if "udevadm control" in c]) == reloads
        assert (st.root / "92-dongle.rules").read_bytes() == u1
        assert (st.root / "dongle.conf").read_bytes() == d1

    def test_legacy_udev_same_pid_retired_with_backup(self, st):
        legacy = st.root / "99-dongle.rules"
        legacy.write_text(
            'SUBSYSTEM=="tty", ENV{ID_MODEL_ID}=="1001", '
            'ENV{ID_USB_INTERFACE_NUM}=="00", SYMLINK+="dongle_if0", '
            'OWNER="asterisk", GROUP="dialout", MODE="0660"\n')
        modem_profile.apply_artifacts(_hprofile())
        assert not legacy.exists()
        assert len(list(st.root.glob("99-dongle.rules.bak-*"))) == 1

    def test_legacy_udev_other_pid_kept(self, st, capsys):
        legacy = st.root / "99-dongle.rules"
        legacy.write_text(
            'SUBSYSTEM=="tty", ENV{ID_MODEL_ID}=="beef", '
            'ENV{ID_USB_INTERFACE_NUM}=="00", SYMLINK+="other0", '
            'OWNER="root", GROUP="root", MODE="0660"\n')
        modem_profile.apply_artifacts(_hprofile())
        assert legacy.exists()  # foreign rule — left for manual review
        out = capsys.readouterr().out
        assert "different modem" in out

    def test_no_vid_pid_skips_udev_with_warning(self, st, capsys):
        res = modem_profile.apply_artifacts(_hprofile(vid_pid="", udev=[]))
        assert res["udev"] is None
        assert not (st.root / "92-dongle.rules").exists()
        assert "NOT rendered" in capsys.readouterr().out


# ---------------------------------------------------------------------------
# use / _switch
# ---------------------------------------------------------------------------

class TestSwitch:
    def test_unverified_refused_without_force(self, st):
        modem_profile.write_profile(_hprofile(verified=False))
        _write_live_yaml(st)
        with pytest.raises(modem_profile.ProfileError, match="NOT verified"):
            modem_profile._switch("huawei-e161", force=False)
        assert not (st.root / "active_modem").exists()
        assert not any("systemctl restart" in c for c in st.calls)

    def test_full_switch_success(self, st, capsys):
        modem_profile.write_profile(_hprofile())
        _write_live_yaml(st)
        (st.root / "active_modem").write_text("old-profile")
        (st.root / "stub_dongle_show").write_text(
            "gsm: 12d1:1001 /dev/dongle_if1 /dev/dongle_if2\n")
        rc = modem_profile._switch("huawei-e161", force=False)
        assert rc == 0
        # surgical yaml update: only the two fields changed
        y = st.yaml()
        assert "  dongle: gsm\n" in y
        assert '  modem_model: "Huawei E161/E169/E620/E800 HSDPA Modem"' \
            in y
        assert "  ring_wait_seconds: 18" in y
        assert (st.root / "active_modem").read_text().strip() == "huawei-e161"
        # restarts: asterisk yes; agent NO (channel name unchanged)
        assert any(c == "systemctl restart asterisk" for c in st.calls)
        assert not any("simbridge-agent" in c and "restart" in c
                       for c in st.calls)
        # globals regenerated by the existing generator
        assert any("generate_asterisk_config.py" in c for c in st.calls)
        assert "SUCCESS" in capsys.readouterr().out

    def test_channel_rename_restarts_agent(self, st):
        modem_profile.write_profile(_hprofile(dongle_name="modem2"))
        _write_live_yaml(st)
        (st.root / "stub_dongle_show").write_text("modem2: ONLINE\n")
        rc = modem_profile._switch("huawei-e161", force=False)
        assert rc == 0
        assert "  dongle: modem2\n" in st.yaml()
        assert any("systemctl restart simbridge-agent" in c
                   for c in st.calls)

    def test_already_active_and_in_sync_is_noop(self, st, capsys):
        p = _hprofile()
        modem_profile.write_profile(p)
        # bring the live state into sync with the profile
        _write_live_yaml(st, LIVE_YAML.replace(
            '  modem_model: "Bus 003 Device 002: ID 12d1:1001 Huawei"',
            '  modem_model: "Huawei E161/E169/E620/E800 HSDPA Modem"'))
        modem_profile.apply_artifacts(p)
        modem_profile.write_active("huawei-e161")
        d_before = (st.root / "dongle.conf").read_bytes()
        rc = modem_profile._switch("huawei-e161", force=False)
        assert rc == 0
        assert not any("systemctl restart" in c for c in st.calls)
        assert (st.root / "dongle.conf").read_bytes() == d_before
        out = capsys.readouterr().out
        assert "already active" in out and "no restarts" in out

    def test_failed_verification_returns_1_and_rollback(self, st, capsys):
        modem_profile.write_profile(_hprofile())
        _write_live_yaml(st)
        (st.root / "active_modem").write_text("old-profile")
        # channel name "gsm" must NOT appear — otherwise verification passes
        (st.root / "stub_dongle_show").write_text("dongle0: OFFLINE\n")
        rc = modem_profile._switch("huawei-e161", force=False)
        assert rc == 1
        out = capsys.readouterr().out
        assert "FAILED" in out
        assert "use old-profile" in out

    def test_missing_profile(self, st):
        _write_live_yaml(st)
        with pytest.raises(modem_profile.ProfileError, match="no such profile"):
            modem_profile._switch("ghost", force=False)


# ---------------------------------------------------------------------------
# probe
# ---------------------------------------------------------------------------

def _stub_quectel(st) -> None:
    (st.root / "stub_tty_devs").write_text(
        "/dev/ttyUSB0\n/dev/ttyUSB1\n/dev/ttyUSB2\n")
    _stub_udev_dev(st, "/dev/ttyUSB0", "01", "2c7c", "0125", "EC25-EU")
    _stub_udev_dev(st, "/dev/ttyUSB1", "02", "2c7c", "0125", "EC25-EU")
    _stub_udev_dev(st, "/dev/ttyUSB2", "03", "2c7c", "0125", "EC25-EU")


class TestProbe:
    def test_finds_at_port_and_usbcfg(self, st, monkeypatch, capsys):
        _stub_quectel(st)
        (st.root / "stub_dongle_show").write_text("gsm: OFFLINE\n")

        def fake_at(dev, cmd, **_kw):
            if dev == "/dev/ttyUSB2":
                if cmd == "AT+CGMM":
                    return "EC25-EU"
                if cmd == 'AT+QCFG="USBCFG"':
                    return 'AT+QCFG: "USBCFG","EC25-EU","QMI,ECM,NTT,PCM,DIAG,MODHEM,AUD,AT,PORT0,PORT1,PORT2,UAC=0"'
            return ""

        monkeypatch.setattr(modem_profile, "at_query", fake_at)
        rc = modem_profile.cmd_probe(
            types.SimpleNamespace(commit="", audio="", data=""))
        assert rc == 0
        out = capsys.readouterr().out
        assert "/dev/ttyUSB2" in out
        assert "UAC=0" in out
        # no commit -> no profile written
        assert not (st.root / "profiles").exists() or \
            not list((st.root / "profiles").glob("*.yaml"))

    def test_commit_writes_unverified_profile(self, st, monkeypatch):
        _stub_quectel(st)
        (st.root / "stub_dongle_show").write_text("gsm: OFFLINE\n")

        def fake_at(dev, cmd, **_kw):
            if dev == "/dev/ttyUSB2":
                return "EC25-EU" if cmd == "AT+CGMM" else ""
            return ""

        monkeypatch.setattr(modem_profile, "at_query", fake_at)
        rc = modem_profile.cmd_probe(types.SimpleNamespace(
            commit="quectel-ec25", audio="/dev/ttyUSB0",
            data="/dev/ttyUSB2"))
        assert rc == 0
        p = modem_profile.load_profile(
            st.root / "profiles" / "quectel-ec25.yaml")
        assert p["vid_pid"] == "2c7c:0125"
        assert p["verified"] is False
        # symlink convention: dongle_if<iface-as-integer>
        assert p["audio_device"] == "/dev/dongle_if1"   # iface 01
        assert p["data_device"] == "/dev/dongle_if3"    # iface 03
        assert p["udev"] == [
            {"iface": "01", "symlink": "dongle_if1"},
            {"iface": "02", "symlink": "dongle_if2"},
            {"iface": "03", "symlink": "dongle_if3"},
        ]

    def test_no_at_port_found_still_reports(self, st, monkeypatch, capsys):
        _stub_quectel(st)
        monkeypatch.setattr(
            modem_profile, "at_query", lambda dev, cmd, **_kw: "")
        rc = modem_profile.cmd_probe(
            types.SimpleNamespace(commit="", audio="", data=""))
        assert rc == 0
        assert "NOT FOUND" in capsys.readouterr().out

    def test_commit_requires_both_ports(self, st, monkeypatch):
        _stub_quectel(st)
        monkeypatch.setattr(
            modem_profile, "at_query", lambda dev, cmd, **_kw: "")
        with pytest.raises(modem_profile.ProfileError):
            modem_profile.cmd_probe(types.SimpleNamespace(
                commit="quectel-ec25", audio="", data=""))

    def test_usbcfg_numeric_decodes_voice_via_nmea(self, st, monkeypatch,
                                                   capsys):
        _stub_quectel(st)
        (st.root / "stub_dongle_show").write_text("gsm: OFFLINE\n")

        def fake_at(dev, cmd, **_kw):
            if dev == "/dev/ttyUSB2":
                if cmd == "AT+CGMM":
                    return "EC25-EU"
                if cmd == 'AT+QCFG="USBCFG"':
                    return '+QCFG: "usbcfg",0x2C7C,0x0125,1,1,1,1,1,0,0'
                if cmd == "AT+QPCMV?":
                    return "+QPCMV: 1,0"
                if cmd == 'AT+QGPSCFG="outport"':
                    return '+QGPSCFG: "outport","none"'
            return ""

        monkeypatch.setattr(modem_profile, "at_query", fake_at)
        rc = modem_profile.cmd_probe(
            types.SimpleNamespace(commit="", audio="", data=""))
        assert rc == 0
        out = capsys.readouterr().out
        assert "nmea=1" in out
        assert "SERIAL PCM via the NMEA port" in out
        assert "serial voice supported" in out
        assert "GNSS output is ON" not in out

    def test_usbcfg_uac_flag_warns_unsupported(self, st, monkeypatch,
                                               capsys):
        _stub_quectel(st)
        (st.root / "stub_dongle_show").write_text("gsm: OFFLINE\n")

        def fake_at(dev, cmd, **_kw):
            if dev == "/dev/ttyUSB2" and cmd == "AT+CGMM":
                return "EC25-EU"
            if dev == "/dev/ttyUSB2" and cmd == 'AT+QCFG="USBCFG"':
                return '+QCFG: "usbcfg",0x2C7C,0x0125,1,1,1,1,1,0,1'
            return ""

        monkeypatch.setattr(modem_profile, "at_query", fake_at)
        modem_profile.cmd_probe(
            types.SimpleNamespace(commit="", audio="", data=""))
        out = capsys.readouterr().out
        assert "uac=1" in out
        assert "CANNOT use it" in out

    def test_gps_outport_warns_when_nmea_in_use(self, st, monkeypatch,
                                                capsys):
        _stub_quectel(st)
        (st.root / "stub_dongle_show").write_text("gsm: OFFLINE\n")

        def fake_at(dev, cmd, **_kw):
            if dev == "/dev/ttyUSB2":
                if cmd == "AT+CGMM":
                    return "EC25-EU"
                if cmd == 'AT+QGPSCFG="outport"':
                    return '+QGPSCFG: "outport","usbnmea"'
            return ""

        monkeypatch.setattr(modem_profile, "at_query", fake_at)
        modem_profile.cmd_probe(
            types.SimpleNamespace(commit="", audio="", data=""))
        out = capsys.readouterr().out
        assert "[warn] GNSS output is ON the USB NMEA port" in out

    def test_guess_prefers_nmea_port_for_verified_ec2x_map(self,
                                                           st, monkeypatch,
                                                           capsys):
        # Live EC25-EU layout: the empirical AT port sits at its canonical
        # slot (iface 02), so the descriptor-doc map is trusted and the
        # guess must name the NMEA port (iface 01) — never the DM port.
        (st.root / "stub_tty_devs").write_text(
            "/dev/ttyUSB0\n/dev/ttyUSB1\n/dev/ttyUSB2\n/dev/ttyUSB3\n")
        for dev, iface in [("/dev/ttyUSB0", "00"), ("/dev/ttyUSB1", "01"),
                           ("/dev/ttyUSB2", "02"), ("/dev/ttyUSB3", "03")]:
            _stub_udev_dev(st, dev, iface, "2c7c", "0125", "EC25-EUX")
        (st.root / "stub_dongle_show").write_text("gsm: OFFLINE\n")

        def fake_at(dev, cmd, **_kw):
            if dev == "/dev/ttyUSB2":
                if cmd == "AT+CGMM":
                    return "EC25-EU"
                if cmd == 'AT+QCFG="USBCFG"':
                    return '+QCFG: "usbcfg",0x2C7C,0x0125,1,1,1,1,1,0,0'
            return ""

        monkeypatch.setattr(modem_profile, "at_query", fake_at)
        rc = modem_profile.cmd_probe(
            types.SimpleNamespace(commit="", audio="", data=""))
        assert rc == 0
        out = capsys.readouterr().out
        assert "audio=/dev/ttyUSB1" in out
        assert "data=/dev/ttyUSB2" in out
        assert "audio=/dev/ttyUSB0" not in out

    def test_gps_outport_warns_when_unquoted(self, st, monkeypatch, capsys):
        # Live firmware answers the value without quotes:
        # '+QGPSCFG: "outport",usbnmea'
        _stub_quectel(st)
        (st.root / "stub_dongle_show").write_text("gsm: OFFLINE\n")

        def fake_at(dev, cmd, **_kw):
            if dev == "/dev/ttyUSB2":
                if cmd == "AT+CGMM":
                    return "EC25-EU"
                if cmd == 'AT+QGPSCFG="outport"':
                    return '+QGPSCFG: "outport",usbnmea'
            return ""

        monkeypatch.setattr(modem_profile, "at_query", fake_at)
        modem_profile.cmd_probe(
            types.SimpleNamespace(commit="", audio="", data=""))
        out = capsys.readouterr().out
        assert "[warn] GNSS output is ON the USB NMEA port" in out


class TestAtQuery:
    """Real pty round-trip — at_query is NOT stubbed here, so the termios
    path (raw mode, cfsetspeed with B* constants, restore in finally) runs
    for real. Regression: CPython's termios exposes cfsetspeed only;
    cfsetispeed/cfsetospeed do not exist and crashed the live probe."""

    @pytest.mark.skipif(not hasattr(os, "ttyname"), reason="needs POSIX pty")
    def test_roundtrip_on_real_pty(self):
        import os
        import pty
        import threading

        master, slave = pty.openpty()
        dev = os.ttyname(slave)
        try:
            def responder():
                try:
                    os.read(master, 256)          # the AT command line
                    os.write(master, b"+CGMM: EC25-EU\r\nOK\r\n")
                except OSError:
                    pass

            threading.Thread(target=responder, daemon=True).start()
            out = modem_profile.at_query(dev, "AT+CGMM", timeout=5)
            assert "EC25-EU" in out
            assert "OK" not in out          # terminal line stripped
        finally:
            os.close(master)
            os.close(slave)

    def test_unopenable_device_returns_empty(self):
        assert modem_profile.at_query("/nonexistent/ttyX", "AT") == ""

    def test_silent_pty_terminates_within_deadline(self):
        """Regression (live EC25 diag port): the call must terminate on the
        timeout even if the tty never delivers data — O_NONBLOCK bounds
        os.read(), which otherwise slept forever in n_tty_read."""
        import pty
        import time

        master, slave = pty.openpty()
        dev = os.ttyname(slave)
        try:
            t0 = time.monotonic()
            out = modem_profile.at_query(dev, "AT+CGMM", timeout=2)
            assert out == ""
            assert time.monotonic() - t0 < 10
        finally:
            os.close(master)
            os.close(slave)


# ---------------------------------------------------------------------------
# capture
# ---------------------------------------------------------------------------

@pytest.fixture
def st_capture(st, monkeypatch):
    """Capture-path state with identity realpath.

    The module resolves /dev symlinks before udevadm (see TestUdevMeta);
    on a node where /dev/dongle_if* exist that resolution would hit the
    real filesystem. Keep the stubbed device names untouched here.
    """
    monkeypatch.setattr(modem_profile.os.path, "realpath", lambda p: str(p))
    return st


class TestParseUdevAll:
    def test_udevadm_record_prefix(self, st):
        # live `udevadm info -q all` prefixes properties with "E: "
        meta = modem_profile.parse_udev_all(
            "P: /devices/pci/usb/tty\nM: ttyUSB0\nR: 0\nU: tty\n"
            'E: ID_MODEL_ID=1001\nE: ID_VENDOR_ID=12d1\n'
            'E: ID_USB_INTERFACE_NUM="01"\nE: ID_MODEL="HUAWEI_Mobile"\n')
        assert meta["ID_MODEL_ID"] == "1001"
        assert meta["ID_VENDOR_ID"] == "12d1"
        assert meta["ID_USB_INTERFACE_NUM"] == "01"
        assert meta["ID_MODEL"] == "HUAWEI_Mobile"
        assert "DEVPATH" not in meta  # P: line has no '='

    def test_plain_key_value(self, st):
        meta = modem_profile.parse_udev_all("ID_MODEL_ID=beef\n")
        assert meta["ID_MODEL_ID"] == "beef"


class TestUdevMeta:
    def test_symlink_resolved_before_query(self, st):
        # live quirk: udevadm given a symlink name returns a reduced
        # property set; the query must go to the resolved device node
        real = st.root / "ttyX"
        real.write_text("")
        link = st.root / "dongle_if1"
        link.symlink_to(real)
        (st.root / "stub_meta_ttyX").write_text(
            "ID_VENDOR_ID=12d1\nID_MODEL_ID=1001\n"
            "ID_USB_INTERFACE_NUM=01\n")
        meta = modem_profile._udev_meta(str(link))
        assert meta["ID_MODEL_ID"] == "1001"
        assert meta["ID_USB_INTERFACE_NUM"] == "01"
        # the udevadm call carried the resolved path, not the symlink
        udev_calls = [c for c in st.calls if "udevadm" in c]
        assert udev_calls
        assert all(str(real) in c for c in udev_calls)
        assert not any(str(link) in c for c in udev_calls)

    def test_non_symlink_passed_through(self, st):
        (st.root / "stub_meta_ttyUSB9").write_text("ID_MODEL_ID=abcd\n")
        meta = modem_profile._udev_meta("/dev/ttyUSB9")
        assert meta["ID_MODEL_ID"] == "abcd"


class TestCapture:
    def _live_state(self, st) -> None:
        (st.root / "dongle.conf").write_text(
            "[general]\ninterval=15\n\n[gsm]\n"
            "audio = /dev/dongle_if1\n"
            "data = /dev/dongle_if2\n"
            "context = incoming-mobile\ngroup = 1\n"
            "smsaspdu = yes\nautodeletesms = yes\n")
        _write_live_yaml(st)
        (st.root / "stub_dongle_ifs").write_text(
            "/dev/dongle_if0\n/dev/dongle_if1\n/dev/dongle_if2\n")
        _stub_udev_dev(st, "/dev/dongle_if0", "00", "12d1", "1001",
                       "E161/E169/E620/E800 HSDPA Modem")
        _stub_udev_dev(st, "/dev/dongle_if1", "01", "12d1", "1001",
                       "E161/E169/E620/E800 HSDPA Modem")
        _stub_udev_dev(st, "/dev/dongle_if2", "02", "12d1", "1001",
                       "E161/E169/E620/E800 HSDPA Modem")

    def test_capture_from_live(self, st_capture):
        st = st_capture
        self._live_state(st)
        p = modem_profile._capture_from_live()
        assert p["dongle_name"] == "gsm"
        assert p["audio_device"] == "/dev/dongle_if1"
        assert p["data_device"] == "/dev/dongle_if2"
        assert p["vid_pid"] == "12d1:1001"
        assert p["sim_phone"] == "+79000000000"
        assert p["verified"] is True
        assert p["udev"] == [
            {"iface": "00", "symlink": "dongle_if0"},
            {"iface": "01", "symlink": "dongle_if1"},
            {"iface": "02", "symlink": "dongle_if2"},
        ]

    def test_vid_pid_fallback_from_model_string(self, st_capture):
        st = st_capture
        self._live_state(st)
        # break the udev source — vid:pid must fall back to the lsusb
        # line stored in sim.modem_model
        for f in st.root.glob("stub_meta_*"):
            f.write_text("ID_MODEL=E161\n")
        p = modem_profile._capture_from_live()
        assert p["vid_pid"] == "12d1:1001"
        assert p["udev"] == []  # no interface map without udev data

    def test_cmd_capture_writes_profile(self, st_capture):
        st = st_capture
        self._live_state(st)
        rc = modem_profile.cmd_capture(
            types.SimpleNamespace(name="huawei-e161", force=False))
        assert rc == 0
        p = modem_profile.load_profile(
            st.root / "profiles" / "huawei-e161.yaml")
        assert p["verified"] is True
        assert p["name"] == "huawei-e161"

    def test_capture_refuses_existing_without_force(self, st):
        self._live_state(st)
        modem_profile.write_profile(_hprofile())
        with pytest.raises(modem_profile.ProfileError, match="already exists"):
            modem_profile.cmd_capture(
                types.SimpleNamespace(name="huawei-e161", force=False))

    def test_capture_without_dongle_conf(self, st):
        _write_live_yaml(st)
        with pytest.raises(modem_profile.ProfileError):
            modem_profile._capture_from_live()


# ---------------------------------------------------------------------------
# list / show / new / init
# ---------------------------------------------------------------------------

class TestListShowNewInit:
    def test_list_marks_active(self, st, capsys):
        modem_profile.write_profile(_hprofile())
        modem_profile.write_profile(_hprofile(name="quectel-ec25",
                                              verified=False,
                                              vid_pid="2c7c:0125"))
        modem_profile.write_active("huawei-e161")
        rc = modem_profile.cmd_list(types.SimpleNamespace())
        assert rc == 0
        out = capsys.readouterr().out
        assert "[ACTIVE] huawei-e161" in out
        assert "[      ] quectel-ec25" in out
        assert "UNVERIFIED" in out

    def test_list_empty(self, st, capsys):
        rc = modem_profile.cmd_list(types.SimpleNamespace())
        assert rc == 0
        assert "no profiles" in capsys.readouterr().out

    def test_show_default_active(self, st, capsys):
        modem_profile.write_profile(_hprofile())
        modem_profile.write_active("huawei-e161")
        rc = modem_profile.cmd_show(types.SimpleNamespace(name=""))
        assert rc == 0
        # scalars are double-quoted by render_profile
        assert 'name: "huawei-e161"' in capsys.readouterr().out

    def test_new_template_unverified(self, st):
        rc = modem_profile.cmd_new(types.SimpleNamespace(
            name="quectel-ec25", modem_model="Quectel EC25-EU",
            vid_pid="2c7c:0125", dongle_name="", audio="", data="",
            sim_phone="", force=False))
        assert rc == 0
        p = modem_profile.load_profile(
            st.root / "profiles" / "quectel-ec25.yaml")
        assert p["verified"] is False
        assert p["vid_pid"] == "2c7c:0125"
        assert [e["symlink"] for e in p["udev"]] == \
            ["dongle_if0", "dongle_if1", "dongle_if2"]

    def test_new_refuses_existing(self, st):
        modem_profile.write_profile(_hprofile())
        with pytest.raises(modem_profile.ProfileError, match="already exists"):
            modem_profile.cmd_new(types.SimpleNamespace(
                name="huawei-e161", modem_model="", vid_pid="",
                dongle_name="", audio="", data="", sim_phone="",
                force=False))

    def test_init_creates_active_and_artifacts(self, st):
        rc = modem_profile.cmd_init(types.SimpleNamespace(
            name="gsm", modem_model="Huawei E161", vid_pid="12d1:1001",
            dongle_name="gsm", audio="", data="", sim_phone="",
            interfaces="00,01,02", force=False))
        assert rc == 0
        assert (st.root / "active_modem").read_text().strip() == "gsm"
        assert (st.root / "dongle.conf").is_file()
        assert (st.root / "92-dongle.rules").is_file()
        p = modem_profile.load_profile(st.root / "profiles" / "gsm.yaml")
        assert p["verified"] is False


# ---------------------------------------------------------------------------
# status
# ---------------------------------------------------------------------------

class TestStatus:
    def test_match_and_mismatch_marking(self, st, capsys):
        modem_profile.write_profile(_hprofile())
        modem_profile.write_active("huawei-e161")
        (st.root / "stub_lsusb").write_text(
            "Bus 003 Device 002: ID 12d1:1001 Huawei Technologies "
            "E161 HSDPA Modem\n")
        (st.root / "stub_dongle_show").write_text("gsm: ONLINE\n")
        rc = modem_profile.cmd_status(types.SimpleNamespace())
        assert rc == 0
        out = capsys.readouterr().out
        assert "12d1:1001" in out
        assert "MATCH" in out

    def test_mismatch(self, st, capsys):
        modem_profile.write_profile(_hprofile())
        modem_profile.write_active("huawei-e161")
        (st.root / "stub_lsusb").write_text(
            "Bus 003 Device 002: ID 2c7c:0125 Quectel EC25-EU\n")
        rc = modem_profile.cmd_status(types.SimpleNamespace())
        assert rc == 0
        assert "MISMATCH" in capsys.readouterr().out

    def test_mm_adoption_warning(self, st, capsys):
        # MM active AND managing a modem → point at the one-time restart.
        modem_profile.write_profile(_hprofile())
        modem_profile.write_active("huawei-e161")
        (st.root / "stub_lsusb").write_text(
            "Bus 003 Device 002: ID 12d1:1001 Huawei E161\n")
        (st.root / "stub_dongle_show").write_text("gsm: Not connec\n")
        (st.root / "stub_mm_active").write_text("active")
        (st.root / "stub_mmcli").write_text(
            "/org/freedesktop/ModemManager1/Modem0 "
            "(quectel /sys/devices/pci0000:00/usb3/3-1)\n")
        rc = modem_profile.cmd_status(types.SimpleNamespace())
        assert rc == 0
        out = capsys.readouterr().out
        assert "/org/freedesktop/ModemManager1/Modem0" in out
        assert "systemctl restart ModemManager" in out

    def test_mm_active_no_modems(self, st, capsys):
        modem_profile.write_profile(_hprofile())
        modem_profile.write_active("huawei-e161")
        (st.root / "stub_lsusb").write_text(
            "Bus 003 Device 002: ID 12d1:1001 Huawei E161\n")
        (st.root / "stub_mm_active").write_text("active")
        rc = modem_profile.cmd_status(types.SimpleNamespace())
        assert rc == 0
        out = capsys.readouterr().out
        assert "no managed modems" in out
        assert "restart ModemManager" not in out

    def test_mm_inactive_silent(self, st, capsys):
        modem_profile.write_profile(_hprofile())
        modem_profile.write_active("huawei-e161")
        (st.root / "stub_lsusb").write_text(
            "Bus 003 Device 002: ID 12d1:1001 Huawei E161\n")
        (st.root / "stub_mm_active").write_text("inactive")
        rc = modem_profile.cmd_status(types.SimpleNamespace())
        assert rc == 0
        assert "ModemManager" not in capsys.readouterr().out
