#!/usr/bin/env python3
"""Generate Asterisk-readable config from simbridge.yaml.

S03.2 — Configurable timings. The dialplan cannot read YAML directly.
This script reads the YAML config and writes asterisk-globals.conf
in Asterisk [globals] format. One generator, no second mechanism.

S03.1 — PROMPT_DURATION: the greeting file (asterisk.prompt) is probed
with the shared ffprobe helper (core.voicemail_forward.ffprobe_duration
— Rule 1, one probe function for all three consumers: this generator,
the sweeper, the forward). The dialplan publishes the result as a
channel variable so the forward can classify speech time and trim the
greeting from the recording. If the file is missing or ffprobe is
unavailable the global is 0.000 (legacy behavior, no trim) and a
warning is printed. Regenerate after swapping the prompt file.

Usage:
    python3 scripts/generate-asterisk-config.py /etc/simbridge/simbridge.yaml

Output: /etc/asterisk/asterisk-globals.conf

Timing equivalence: chan_dongle ring cycles are ~5 seconds each.
    ring_wait_seconds=24 ≈ 5 ring cycles (matches GPT doc spec).
"""

from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

import yaml

# core/ sits next to scripts/ in the deployed tree and the repo. When
# run as `python .../scripts/generate_asterisk_config.py` only scripts/
# is on sys.path, so add the app root explicitly (stdlib-only import).
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from core.voicemail_forward import ffprobe_duration  # noqa: E402

OUTPUT_HEADER = """\
; SimBridge — auto-generated Asterisk globals
; Generated by scripts/generate-asterisk-config.py
; Do NOT edit manually. Change values in simbridge.yaml instead.
"""


def load_yaml(path: str) -> dict:
    with open(path) as fh:
        return yaml.safe_load(fh)


def generate(config: dict, output_path: str) -> None:
    a = config.get("asterisk", {})

    ring_wait = int(a.get("ring_wait_seconds", 24))
    max_record = int(a.get("max_record_seconds", 90))
    early_hangup = int(a.get("early_hangup_max_seconds", 3))
    prompt = a.get("prompt", "/var/lib/asterisk/sounds/custom/vm-prompt")

    # Strip codec extension for Playback() — Playback() auto-selects
    # and doesn't want the .ulaw suffix
    prompt_path = prompt.rsplit(".", 1)[0] if "." in prompt.split("/")[-1] else prompt

    # S03.1: probe the greeting length (the full path, extension-based
    # format hint). 0.0 when the file is missing or ffprobe is absent
    # — the dialplan then classifies/trims as before (legacy behavior).
    prompt_duration = ffprobe_duration(prompt) if prompt else 0.0
    if prompt and prompt_duration <= 0.0:
        print(f"WARNING: cannot probe prompt {prompt} — "
              f"PROMPT_DURATION=0.000 (no greeting trim)")

    # Bridge settings (S04.2)
    voice = config.get("voice", {})
    bridge_endpoint = voice.get("bridge_endpoint", "tg-bridge")
    bridge_host = voice.get("bridge_host", "127.0.0.1")
    bridge_port = int(voice.get("bridge_port", 5062))
    outbound_timeout = int(voice.get("outbound_answer_timeout", 30))
    # S04.3: max seconds the GSM number may ring on an outgoing call
    outbound_gsm_ring = int(voice.get("outbound_gsm_ring_seconds", 30))

    content = OUTPUT_HEADER
    content += "[globals]\n"
    content += f"; Timing: ring_wait_seconds={ring_wait} (≈ {ring_wait // 5} ring cycles)\n"
    content += f"RING_WAIT_SECONDS={ring_wait}\n"
    content += f"MAX_RECORD_SECONDS={max_record}\n"
    content += f"EARLY_HANGUP_MAX_SECONDS={early_hangup}\n"
    content += f"VM_PROMPT={prompt_path}\n"
    content += (f"; S03.1: greeting length in seconds (probed) — the AGI "
                f"trims this many seconds from the front of the recording\n")
    content += f"PROMPT_DURATION={prompt_duration:.3f}\n"
    content += f"VM_REC_DIR={config.get('paths', {}).get('recordings_dir', '/var/lib/simbridge/recordings')}\n"
    content += f"; Bridge (S04.2): Telegram voice bridge settings\n"
    content += f"BRIDGE_ENDPOINT={bridge_endpoint}\n"
    content += f"BRIDGE_HOST={bridge_host}\n"
    content += f"BRIDGE_PORT={bridge_port}\n"
    content += f"OUTBOUND_RING_TIMEOUT={outbound_timeout}\n"
    content += f"; S04.3: max seconds the GSM number may ring on an outgoing call\n"
    content += f"OUTBOUND_GSM_RING_SECONDS={outbound_gsm_ring}\n"
    # S04.3: Call duration limit
    limits = config.get("limits", {})
    max_call = int(limits.get("max_call_seconds", 1800))
    content += f"; Call limits (S04.3)\n"
    content += f"MAX_CALL_SECONDS={max_call}\n"
    # S04.4: Distributed mode — Tailscale network settings
    content += f"; Distributed mode (S04.4): Tailscale network\n"
    content += f"TAILNET_CGNAT=100.64.0.0/10\n"
    # S01: event forwarding targets (P0-3: AGI scripts read these via
    # channel variables — FWD_URL, MODEM_ID — never hardcode in the dialplan)
    userbot_listen = config.get("userbot_http", {}).get("listen", "127.0.0.1:8088")
    content += f"; Userbot HTTP (SMS/voicemail event forwarding)\n"
    content += f"USERBOT_URL=http://{userbot_listen}\n"
    paths = config.get("paths", {})
    blacklist = paths.get("blacklist", "/etc/simbridge/blacklist.txt")
    content += f"; Blacklist file (S02.2: incoming call/SMS check)\n"
    content += f"BLACKLIST_PATH={blacklist}\n"
    content += f"; Modem ID for event payloads (single-dongle S01)\n"
    content += f"MODEM_ID={a.get('dongle', 'gsm')}\n"

    out = Path(output_path)
    out.write_text(content, encoding="utf-8")
    print(f"Written: {output_path}")
    print(f"  RING_WAIT_SECONDS = {ring_wait} ({ring_wait // 5} ring cycles)")
    print(f"  MAX_RECORD_SECONDS = {max_record}")
    print(f"  EARLY_HANGUP_MAX_SECONDS = {early_hangup}")
    print(f"  VM_PROMPT = {prompt_path}")
    print(f"  PROMPT_DURATION = {prompt_duration:.3f}")
    print(f"  BRIDGE_ENDPOINT = {bridge_endpoint}")
    print(f"  OUTBOUND_RING_TIMEOUT = {outbound_timeout}")
    print(f"  OUTBOUND_GSM_RING_SECONDS = {outbound_gsm_ring}")
    print(f"  USERBOT_URL = http://{userbot_listen}")
    print(f"  BLACKLIST_PATH = {blacklist}")
    print(f"  MODEM_ID = {a.get('dongle', 'gsm')}")


PJSIP_HEADER = """\
; SimBridge — auto-generated PJSIP config (S04.2)
; Generated by scripts/generate-asterisk-config.py
; Do NOT edit manually. Change values in simbridge.yaml instead.
;
; The Telegram voice bridge (blitss/sip-tg-bridge) speaks PJSIP in both
; roles:
;   - UAS: it answers this endpoint's INVITE on incoming calls
;     (the dialplan Dials SIP/<endpoint>; the bridge rings Telegram)
;   - UAC: it INVITEs this node for outgoing calls, target number as
;     Request-URI user -> context <endpoint>, exten = target number
; Both directions therefore authenticate: outbound_auth authenticates
; Asterisk towards the bridge, auth authenticates the bridge towards
; Asterisk (an unauthenticated INVITE could dial arbitrary GSM numbers
; through the modem).
"""

BRIDGE_SECRET_ENV = "SIMBRIDGE_BRIDGE_SECRET"
NODE_IP_ENV = "SIMBRIDGE_NODE_TAILSCALE_IP"


def generate_pjsip(
    config: dict,
    output_path: str,
    bridge_secret: str,
    node_ip: str = "",
) -> None:
    """Generate pjsip.conf for the Telegram voice bridge endpoint (S04.2).

    ``bridge_secret`` (env ``SIMBRIDGE_BRIDGE_SECRET``, Rule 5) is the
    shared SIP credential; generation is refused without it. ``node_ip``
    (env ``SIMBRIDGE_NODE_TAILSCALE_IP``) becomes ``external_media_addr``
    in distributed mode so RTP leaves via the Tailscale interface.
    """
    if not bridge_secret:
        print(
            f"ERROR: {BRIDGE_SECRET_ENV} is not set — refusing to write "
            f"pjsip.conf without a bridge credential (Rule 5).",
            file=sys.stderr,
        )
        sys.exit(1)

    voice = config.get("voice", {})
    endpoint = voice.get("bridge_endpoint", "tg-bridge")
    bridge_host = voice.get("bridge_host", "127.0.0.1")
    bridge_port = int(voice.get("bridge_port", 5062))
    auth_name = f"{endpoint}-auth"
    aor_name = f"{endpoint}-aor"

    distributed = bridge_host != "127.0.0.1"
    # Single node: the bridge runs on this host and reaches Asterisk on
    # loopback, so a loopback-only bind. Distributed: the bridge is on
    # the other node and reaches SIP over Tailscale — wildcard bind,
    # protected by the mandatory inbound auth (see module header above).
    bind_addr = "0.0.0.0" if distributed else "127.0.0.1"

    content = PJSIP_HEADER
    content += "[global]\n"
    content += "user_agent=SimBridge\n"
    content += "\n"
    content += "[transport-udp]\n"
    content += "protocol=udp\n"
    content += f"bind={bind_addr}\n"
    content += "\n"
    content += f"[{endpoint}]\n"
    content += "transport=transport-udp\n"
    content += f"context={endpoint}\n"
    content += "disallow=all\n"
    content += "allow=ulaw,alaw\n"
    content += "dtmf_mode=rfc2833\n"
    content += "; S04.2: the bridge must transcode — media must NOT be\n"
    content += "; redirected between the caller and the bridge (no direct\n"
    content += "; RTP). Asterisk stays on the media path.\n"
    content += "direct_media=no\n"
    content += "rtptimeout=60\n"
    content += "rtpholdtimeout=30\n"
    content += "ice_support=no\n"
    content += "; S04.4: Tailscale CGNAT range is local; apply NAT options\n"
    content += "; (comedia) so RTP traverses the tailnet correctly\n"
    content += "local_net=100.64.0.0/10\n"
    content += "nat_option=rtp\n"
    if distributed and node_ip:
        content += f"external_media_addr={node_ip}\n"
    content += f"auth={auth_name}\n"
    content += f"outbound_auth={auth_name}\n"
    content += f"aors={aor_name}\n"
    content += "\n"
    content += f"[{auth_name}]\n"
    content += "auth_type=userpass\n"
    content += "username=tg-bridge\n"
    content += f"password={bridge_secret}\n"
    content += "\n"
    content += f"[{aor_name}]\n"
    content += "max_contacts=1\n"
    content += f"contact=sip:{bridge_host}:{bridge_port}\n"
    content += "qualify=no\n"

    out = Path(output_path)
    out.write_text(content, encoding="utf-8")
    print(f"Written: {output_path}")
    print(f"  [{endpoint}] context={endpoint} direct_media=no bind={bind_addr}")
    print(f"  [{aor_name}] contact=sip:{bridge_host}:{bridge_port}")
    if distributed and not node_ip:
        print(
            f"WARNING: {NODE_IP_ENV} not set in distributed mode — "
            f"RTP may leave via the wrong interface"
        )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("config", help="Path to simbridge.yaml")
    parser.add_argument(
        "-o", "--output",
        default="/etc/asterisk/asterisk-globals.conf",
        help="Output path for generated config (default: /etc/asterisk/asterisk-globals.conf)",
    )
    parser.add_argument(
        "-p", "--pjsip-out",
        default=None,
        help="Also generate pjsip.conf for the voice bridge at this path "
             "(reads SIMBRIDGE_BRIDGE_SECRET, and optionally "
             "SIMBRIDGE_NODE_TAILSCALE_IP, from the environment)",
    )
    args = parser.parse_args()

    config = load_yaml(args.config)
    generate(config, args.output)
    if args.pjsip_out:
        generate_pjsip(
            config,
            args.pjsip_out,
            bridge_secret=os.environ.get(BRIDGE_SECRET_ENV, ""),
            node_ip=os.environ.get(NODE_IP_ENV, ""),
        )


if __name__ == "__main__":
    main()
