#!/usr/bin/env python3
"""Generate Asterisk-readable config from simbridge.yaml.

S03.2 — Configurable timings. The dialplan cannot read YAML directly.
This script reads the YAML config and writes asterisk-globals.conf
in Asterisk [globals] format. One generator, no second mechanism.

Usage:
    python3 scripts/generate-asterisk-config.py /etc/simbridge/simbridge.yaml

Output: /etc/asterisk/asterisk-globals.conf

Timing equivalence: chan_dongle ring cycles are ~5 seconds each.
    ring_wait_seconds=24 ≈ 5 ring cycles (matches GPT doc spec).
"""

from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

import yaml

OUTPUT_HEADER = """\
; SimBridge — auto-generated Asterisk globals
; Generated by scripts/generate-asterisk-config.py
; Do NOT edit manually. Change values in simbridge.yaml instead.
"""


def load_yaml(path: str) -> dict:
    with open(path) as fh:
        return yaml.safe_load(fh)


def generate(config: dict, output_path: str) -> None:
    a = config.get("asterisk", {})

    ring_wait = int(a.get("ring_wait_seconds", 24))
    max_record = int(a.get("max_record_seconds", 90))
    prompt = a.get("prompt", "/var/lib/asterisk/sounds/custom/vm-prompt")

    # Strip codec extension for Playback() — Playback() auto-selects
    # and doesn't want the .ulaw suffix
    prompt_path = prompt.rsplit(".", 1)[0] if "." in prompt.split("/")[-1] else prompt

    content = OUTPUT_HEADER
    content += "[globals]\n"
    content += f"; Timing: ring_wait_seconds={ring_wait} (≈ {ring_wait // 5} ring cycles)\n"
    content += f"RING_WAIT_SECONDS={ring_wait}\n"
    content += f"MAX_RECORD_SECONDS={max_record}\n"
    content += f"VM_PROMPT={prompt_path}\n"
    content += f"VM_REC_DIR={config.get('paths', {}).get('recordings_dir', '/var/lib/simbridge/recordings')}\n"

    out = Path(output_path)
    out.write_text(content, encoding="utf-8")
    print(f"Written: {output_path}")
    print(f"  RING_WAIT_SECONDS = {ring_wait} ({ring_wait // 5} ring cycles)")
    print(f"  MAX_RECORD_SECONDS = {max_record}")
    print(f"  VM_PROMPT = {prompt_path}")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("config", help="Path to simbridge.yaml")
    parser.add_argument(
        "-o", "--output",
        default="/etc/asterisk/asterisk-globals.conf",
        help="Output path for generated config (default: /etc/asterisk/asterisk-globals.conf)",
    )
    args = parser.parse_args()

    config = load_yaml(args.config)
    generate(config, args.output)


if __name__ == "__main__":
    main()
