#!/usr/bin/env python3
"""Modem profile manager — per-modem config with one-command swap.

SimBridge runs on a USB GSM modem. Everything that is modem-specific
lives in four places:

  1. /etc/udev/rules.d/92-dongle.rules   — VID/PID + USB interface number
                                            -> stable dongle_ifN symlinks,
                                            owner asterisk:dialout
  2. /etc/asterisk/dongle.conf           — channel name + voice (audio=
                                            serial PCM tty, or alsadev=
                                            UAC ALSA card) + data= devices
  3. /etc/simbridge/simbridge.yaml       — asterisk.dongle, sim.modem_model
  4. /etc/asterisk/asterisk-globals.conf — MODEM_ID (generated from #3 by
                                            scripts/generate_asterisk_config.py)

A *profile* is a YAML file with all of the above in one record:

  /etc/simbridge/modem-profiles/<name>.yaml
  /etc/simbridge/active_modem             (one-line pointer to the active name)

Subcommands:

  list                          show all profiles, mark the active one
  show [name]                   print a profile (default: active)
  status                        active profile vs. plugged-in USB device,
                                dongle + agent state
  new <name>                    create an unverified template profile
  capture <name>                create a verified profile from the live
                                state (the currently working modem)
  probe [--commit <name>]       inspect the plugged-in modem (ports, AT
                                answers, USBCFG); --commit writes/updates
                                the profile from the findings
  init <name> ...               (used by deploy/install.py) create a profile
                                from installer answers and render artifacts
  apply <name>                  re-render udev rules + dongle.conf for a
                                profile, no service restarts
  use <name> [--force]          SWITCH: back up -> render artifacts ->
                                update simbridge.yaml -> regenerate globals
                                -> restart services -> verify -> report

Rules honored:
  Rule 1 — this script is the ONLY mechanism that renders dongle.conf and
           the dongle udev rules. deploy/install.py (fresh installs) calls
           `init` instead of writing the files itself; the globals are
           regenerated by the existing scripts/generate_asterisk_config.py.
  Rule 2 — a profile is `verified: true` only after a live end-to-end
           check; `use` refuses an unverified profile without --force.
  Rule 4 — `use` backs up every file it changes (timestamped .bak-*) and
           is idempotent: switching to the already-active profile whose
           artifacts are in sync changes nothing and restarts nothing.
  Rule 5 — profiles contain no secrets.

Live swap workflow (modem physically replaced):

  python3 modem_profile.py probe                 # inspect the new modem
  python3 modem_profile.py probe --commit quectel-ec25 --data /dev/ttyUSB2
                                                 # fix the profile
  python3 modem_profile.py use quectel-ec25 --force
  # on failure: put the old modem back, then
  python3 modem_profile.py use huawei-e161

Test hooks (used by tests/test_modem_profile.py): all state paths can be
redirected via environment variables, and all shell commands go through
the single run() function so tests can stub it.
"""

from __future__ import annotations

import argparse
import os
import re
import select
import shlex
import subprocess
import sys
import time
from datetime import datetime, timezone
from pathlib import Path

import yaml

# ---------------------------------------------------------------------------
# State paths — env-overridable so tests can run in a temp directory.
# ---------------------------------------------------------------------------

PROFILES_DIR_DEFAULT = "/etc/simbridge/modem-profiles"
ACTIVE_POINTER_DEFAULT = "/etc/simbridge/active_modem"
DONGLE_CONF_DEFAULT = "/etc/asterisk/dongle.conf"
UDEV_RULE_DEFAULT = "/etc/udev/rules.d/92-dongle.rules"
UDEV_LEGACY_RULE_DEFAULT = "/etc/udev/rules.d/99-dongle.rules"
CONFIG_YAML_DEFAULT = "/etc/simbridge/simbridge.yaml"
GLOBALS_DEFAULT = "/etc/asterisk/asterisk-globals.conf"


def paths() -> dict:
    """Current state paths (read on every call — tests set env per-test)."""
    return {
        "profiles_dir": Path(os.environ.get("SIMBRIDGE_PROFILE_DIR",
                                            PROFILES_DIR_DEFAULT)),
        "active": Path(os.environ.get("SIMBRIDGE_ACTIVE_MODEM",
                                      ACTIVE_POINTER_DEFAULT)),
        "dongle_conf": Path(os.environ.get("SIMBRIDGE_DONGLE_CONF",
                                           DONGLE_CONF_DEFAULT)),
        "udev_rule": Path(os.environ.get("SIMBRIDGE_UDEV_RULE",
                                         UDEV_RULE_DEFAULT)),
        "udev_legacy_rule": Path(os.environ.get("SIMBRIDGE_UDEV_RULE_LEGACY",
                                                UDEV_LEGACY_RULE_DEFAULT)),
        "config_yaml": Path(os.environ.get("SIMBRIDGE_CONFIG",
                                           CONFIG_YAML_DEFAULT)),
        "globals": Path(os.environ.get("SIMBRIDGE_ASTERISK_GLOBALS",
                                       GLOBALS_DEFAULT)),
    }


GENERATOR = Path(__file__).resolve().parent / "generate_asterisk_config.py"

# App-level chan_dongle behavior — NOT modem-specific. Kept in sync with
# asterisk/dongle.conf.example (the example documents the rationale).
DONGLE_INTERVAL = 15          # [general] discovery loop poll, seconds
DONGLE_CONTEXT = "incoming-mobile"
DONGLE_GROUP = 1


class ProfileError(Exception):
    """Invalid profile or state; main() prints it and exits 1."""


# ---------------------------------------------------------------------------
# Shell — every external command goes through run() (tests stub this).
# ---------------------------------------------------------------------------

def run(cmd: str, timeout: int = 30) -> "subprocess.CompletedProcess":
    """Run *cmd* in a shell, capturing output. Never raises."""
    try:
        return subprocess.run(cmd, shell=True, capture_output=True,
                              text=True, timeout=timeout)
    except subprocess.TimeoutExpired:
        return subprocess.CompletedProcess(cmd, 124, "", f"timeout after {timeout}s")


def _write_atomic(path: Path, text: str, mode: int) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_name(path.name + ".tmp")
    tmp.write_text(text)
    tmp.chmod(mode)
    os.replace(tmp, path)


def backup(path: Path) -> str:
    """Copy *path* to <path>.bak-<UTC timestamp>. '' if source missing."""
    if not path.is_file():
        return ""
    ts = datetime.now(timezone.utc).strftime("%Y%m%d-%H%M%S")
    bak = path.with_name(path.name + f".bak-{ts}")
    bak.write_bytes(path.read_bytes())
    try:
        bak.chmod(path.stat().st_mode & 0o777)
    except OSError:
        pass
    return str(bak)


# ---------------------------------------------------------------------------
# Profile schema, validation, serialization
# ---------------------------------------------------------------------------

def validate_profile(p: dict) -> list:
    """Return a list of error strings (empty = valid)."""
    errors = []
    for k in ("name", "modem_model", "dongle_name", "data_device"):
        if not isinstance(p.get(k), str) or not p.get(k).strip():
            errors.append(f"{k}: required non-empty string")
    # Voice path: exactly one of audio_device (serial PCM tty) or alsadev
    # (UAC ALSA card, chan_dongle patch 0003) — never both, never neither.
    audio = p.get("audio_device")
    alsadev = p.get("alsadev")
    if not isinstance(audio, str):
        audio = ""
    if alsadev is not None and not isinstance(alsadev, str):
        errors.append("alsadev: must be a string (empty = serial audio tty)")
        alsadev = ""
    alsadev = alsadev or ""
    if not audio.strip():
        if not alsadev:
            errors.append("audio_device: required non-empty string "
                          "(or set alsadev for UAC voice)")
    elif alsadev:
        errors.append("audio_device and alsadev are mutually exclusive "
                      "(UAC voice uses the ALSA card, not a serial tty)")
    if alsadev and re.search(r"\s", alsadev):
        errors.append("alsadev: must not contain whitespace "
                      "(e.g. hw:CARD=EC25EUX,DEV=0)")
    name = p.get("name") or ""
    if isinstance(name, str) and name and \
            not re.fullmatch(r"[a-z0-9][a-z0-9-]*", name):
        errors.append("name: must match [a-z0-9][a-z0-9-]* (lowercase, dashes)")
    vid = p.get("vid_pid", "")
    if vid is None:
        vid = ""
    if vid and not re.fullmatch(r"[0-9a-fA-F]{4}:[0-9a-fA-F]{4}", str(vid)):
        errors.append(f"vid_pid: {vid!r} — must be 'vvvv:pppp' or empty")
    if not isinstance(p.get("verified"), bool):
        errors.append("verified: required boolean (true only after live E2E)")
    udev = p.get("udev", [])
    if not isinstance(udev, list):
        errors.append("udev: required list of {iface, symlink} (may be empty)")
    else:
        for i, e in enumerate(udev):
            if not isinstance(e, dict):
                errors.append(f"udev[{i}]: must be a mapping")
                continue
            if not re.fullmatch(r"\d{2}", str(e.get("iface", ""))):
                errors.append(
                    f"udev[{i}].iface: required 2-digit USB interface number")
            if not isinstance(e.get("symlink"), str) or not e.get("symlink"):
                errors.append(f"udev[{i}].symlink: required non-empty string")
    return errors


def _ys(v) -> str:
    """Double-quoted single-line YAML scalar (safe for colons/spaces)."""
    return '"' + str(v).replace("\\", "\\\\").replace('"', '\\"') + '"'


def render_profile(p: dict) -> str:
    """Serialize a profile dict to its on-disk YAML (fixed key order)."""
    lines = [
        f"# SimBridge modem profile — {p['name']}",
        "# Written by scripts/modem_profile.py (new/capture/probe/init).",
        "# 'verified' means a live end-to-end test on this modem passed.",
        "name: " + _ys(p["name"]),
        "modem_model: " + _ys(p.get("modem_model", "")),
        "vid_pid: " + _ys(p.get("vid_pid", "")),
        f"dongle_name: {p['dongle_name']}",
        f"audio_device: {p['audio_device']}",
        f"data_device: {p['data_device']}",
    ]
    # alsadev only for UAC profiles — an empty line would break the
    # render/load roundtrip on serial profiles
    if p.get("alsadev"):
        lines.append("alsadev: " + _ys(p["alsadev"]))
    lines += [
        "sim_phone: " + _ys(p.get("sim_phone", "")),
        "udev:",
    ]
    for e in p.get("udev", []):
        lines.append(f'  - {{iface: "{e["iface"]}", symlink: {e["symlink"]}}}')
    if not p.get("udev"):
        lines[-1] = "udev: []"
    lines.append(f"verified: {str(p['verified']).lower()}")
    lines.append("notes: " + _ys(p.get("notes", "")))
    return "\n".join(lines) + "\n"


def load_profile(path: Path) -> dict:
    with open(path) as fh:
        p = yaml.safe_load(fh)
    if not isinstance(p, dict):
        raise ProfileError(f"invalid profile (not a mapping): {path}")
    errs = validate_profile(p)
    if errs:
        raise ProfileError(f"invalid profile {path}:\n  - " + "\n  - ".join(errs))
    # 'audio_device: ' (UAC profiles) parses to None — normalize to ""
    p["audio_device"] = p.get("audio_device") or ""
    p.setdefault("vid_pid", "")
    p.setdefault("sim_phone", "")
    p.setdefault("udev", [])
    p.setdefault("notes", "")
    return p


def profile_path(name: str) -> Path:
    if not re.fullmatch(r"[a-z0-9][a-z0-9-]*", name or ""):
        raise ProfileError(f"invalid profile name: {name!r}")
    return paths()["profiles_dir"] / f"{name}.yaml"


def write_profile(p: dict) -> Path:
    errs = validate_profile(p)
    if errs:
        raise ProfileError("invalid profile:\n  - " + "\n  - ".join(errs))
    path = profile_path(p["name"])
    _write_atomic(path, render_profile(p), 0o644)
    return path


def read_active() -> str:
    p = paths()["active"]
    if p.is_file():
        name = p.read_text().strip()
        if name:
            return name
    return ""


def write_active(name: str) -> None:
    p = paths()["active"]
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(name + "\n")
    p.chmod(0o644)


# ---------------------------------------------------------------------------
# Renderers — the single source for dongle.conf and the dongle udev rules
# (Rule 1: install.py calls `init`, nobody else writes these files).
# ---------------------------------------------------------------------------

def render_dongle_conf(p: dict) -> str:
    """Render /etc/asterisk/dongle.conf for profile *p*.

    Modem-specific: the channel name and the voice/data devices. Voice
    is either audio=<serial PCM tty> or alsadev=<ALSA card> (UAC,
    chan_dongle patch 0003) — the profile carries one or the other.
    App-level constants mirror asterisk/dongle.conf.example.
    """
    vid = p.get("vid_pid") or "unknown vid:pid"
    n = p["dongle_name"]
    alsadev = p.get("alsadev") or ""
    voice_line = (f"alsadev = {alsadev}\n" if alsadev
                  else f"audio = {p['audio_device']}\n")
    return (
        "; SimBridge chan_dongle config — GENERATED by scripts/modem_profile.py\n"
        f"; Profile: {p['name']} — {p.get('modem_model', '')} ({vid})\n"
        "; Do NOT edit manually. To swap modems:\n"
        ";   python3 /opt/simbridge/scripts/modem_profile.py use <profile>\n"
        "; App constants mirror asterisk/dongle.conf.example.\n"
        "\n"
        "[general]\n"
        f"interval={DONGLE_INTERVAL}\n"
        "\n"
        f"[{n}]\n"
        f"{voice_line}"
        f"data = {p['data_device']}\n"
        f"context = {DONGLE_CONTEXT}\n"
        f"group = {DONGLE_GROUP}\n"
        "smsaspdu = yes\n"
        "autodeletesms = yes\n"
    )


UDEV_RULE_TEMPLATE = (
    'SUBSYSTEM=="tty", ENV{{ID_MODEL_ID}}=="{pid}", '
    'ENV{{ID_USB_INTERFACE_NUM}}=="{iface}", SYMLINK+="{symlink}", '
    'OWNER="asterisk", GROUP="dialout", MODE="0660"'
)

# Tag telling ModemManager to leave this modem alone. chan_dongle owns the
# AT/audio ports; when MM probes the dongle it holds the AT port open and
# chan_dongle then fails to open it (EBUSY) — observed live with the EC25,
# whose vendor rules (77-mm-quectel-port-types.rules) mark the AT port with
# high confidence, so even the strict filter policy (the MM default) probes
# it. ID_MM_DEVICE_IGNORE is honored under all filter policies, strict
# included (mm-filter.c: mm_filter_port() checks it before the plugin
# allowlists, under MM_FILTER_RULE_EXPLICIT_BLOCKLIST).
#
# The tag must be present on the PORTS themselves, not only on the USB
# composite device. On RHEL9 (MM 1.20.2) the filter's physdev lookup
# (kernel_device_get_global_property → first devtype "usb_device" ancestor)
# did not surface the composite's udev properties even though the tag was
# in the udev DB at the fresh plug-in event — the modem was created
# anyway, and MM kept the AT port open. What IS reliably visible to the
# filter is the port's own property list (the vendor rules'
# ID_MM_PORT_TYPE_* tags on the tty devices are what MM acted on).
# udev ATTR{} matches a device's own attributes, ATTRS{} its ancestors'
# (udev(7)) — so two rules are needed to cover both the composite and
# every device in its subtree (tty, usbmisc/QMI, net ports alike):
UDEV_MM_IGNORE_SELF_TEMPLATE = (
    'SUBSYSTEM=="usb", ATTR{{idVendor}}=="{vid}", '
    'ATTR{{idProduct}}=="{pid}", ENV{{ID_MM_DEVICE_IGNORE}}="1"'
)
UDEV_MM_IGNORE_SUBTREE_TEMPLATE = (
    'ATTRS{{idVendor}}=="{vid}", '
    'ATTRS{{idProduct}}=="{pid}", ENV{{ID_MM_DEVICE_IGNORE}}="1"'
)


def render_udev_rules(p: dict) -> str:
    """Render /etc/udev/rules.d/92-dongle.rules for profile *p*.

    The per-port symlink rules are keyed by ID_MODEL_ID (the USB PID —
    stable across ports and firmware updates of the same model) plus
    ID_USB_INTERFACE_NUM (the interface number — stable; the ttyUSB
    index is NOT). Two ID_MM_DEVICE_IGNORE rules keep ModemManager off
    the dongle: one on the USB composite device (ATTR = own attributes),
    one on every device in its subtree (ATTRS = ancestor attributes) —
    see UDEV_MM_IGNORE_*_TEMPLATE for why both are needed.
    """
    parts = (p.get("vid_pid") or "").split(":")
    vid = parts[0] if len(parts) == 2 else ""
    pid = parts[1] if len(parts) == 2 else ""
    if not pid:
        raise ProfileError(f"profile {p['name']}: no vid_pid — "
                           "cannot render udev rules")
    if not p.get("udev"):
        raise ProfileError(f"profile {p['name']}: empty udev mapping")
    lines = [
        "# SimBridge dongle symlinks — GENERATED by scripts/modem_profile.py",
        f"# Profile: {p['name']} — {p.get('modem_model', '')} "
        f"({p.get('vid_pid', '')})",
        "# Do NOT edit manually.",
    ]
    if vid:
        lines.append(UDEV_MM_IGNORE_SELF_TEMPLATE.format(vid=vid, pid=pid))
        lines.append(UDEV_MM_IGNORE_SUBTREE_TEMPLATE.format(vid=vid, pid=pid))
    for e in p["udev"]:
        lines.append(UDEV_RULE_TEMPLATE.format(pid=pid, iface=e["iface"],
                                               symlink=e["symlink"]))
    return "\n".join(lines) + "\n"


def _retire_legacy_udev_rule(p: dict) -> None:
    """Remove the S01-era duplicate 99-dongle.rules when (and only when)
    it keys the same USB PID as the active profile."""
    legacy = paths()["udev_legacy_rule"]
    if not legacy.is_file():
        return
    pid = (p.get("vid_pid") or "").split(":")[1]
    # udev ENV{} syntax: the closing brace sits between the key and ==
    m = re.search(r'ID_MODEL_ID\}=="([0-9a-fA-F]{4})"',
                  legacy.read_text(errors="replace"))
    if m and pid and m.group(1).lower() == pid.lower():
        b = backup(legacy)
        legacy.unlink()
        print(f"  Retired legacy duplicate rule: {legacy}"
              + (f" (backup {b})" if b else ""))
    elif m:
        print(f"  [warn] {legacy.name} keys a different modem "
              f"(PID {m.group(1)}) — left untouched, review manually")


def apply_artifacts(p: dict, backup_old: bool = True) -> dict:
    """Render udev rules + dongle.conf from profile *p*.

    Shared by `use` (full switch) and `init`/`apply` (fresh install /
    manual re-render). Never restarts services — the caller decides.
    Returns {"backups": [...], "udev": path-or-None, "dongle_conf": path}.
    """
    ps = paths()
    backups = []
    if backup_old:
        for f in (ps["udev_rule"], ps["dongle_conf"], ps["config_yaml"],
                  ps["active"]):
            b = backup(f)
            if b:
                backups.append(b)

    udev_written = None
    if p.get("vid_pid") and p.get("udev"):
        udev_text = render_udev_rules(p)
        if not ps["udev_rule"].is_file() \
                or ps["udev_rule"].read_text() != udev_text:
            _write_atomic(ps["udev_rule"], udev_text, 0o644)
            udev_written = str(ps["udev_rule"])
            # Scoped trigger: only the two subsystems these rules act on —
            # tty (symlink rules) and usb (the ID_MM_DEVICE_IGNORE rule on
            # the physical device; ModemManager needs that change event to
            # drop a device it has already adopted). A bare `udevadm
            # trigger` re-fires every device on the box, too wide for a
            # live node.
            r = run("udevadm control --reload-rules && "
                    "udevadm trigger --subsystem-match=tty "
                    "--subsystem-match=usb")
            if r.returncode != 0:
                print("  [warn] udevadm reload/trigger: "
                      f"{(r.stdout or r.stderr).strip()[:200]}")
        _retire_legacy_udev_rule(p)
    else:
        print("  [warn] profile has no vid_pid/udev mapping — udev rules "
              "NOT rendered; set up symlinks/permissions manually")

    dtext = render_dongle_conf(p)
    if not ps["dongle_conf"].is_file() \
            or ps["dongle_conf"].read_text() != dtext:
        _write_atomic(ps["dongle_conf"], dtext, 0o644)
    return {"backups": backups, "udev": udev_written,
            "dongle_conf": str(ps["dongle_conf"])}


# ---------------------------------------------------------------------------
# simbridge.yaml — line-based surgical patch (all other bytes identical)
# ---------------------------------------------------------------------------

def _yaml_field(text: str, section: str, key: str) -> str:
    """Value of `key` inside top-level `section:`, unquoted, '' if absent."""
    in_section = False
    for line in text.splitlines():
        if not line.startswith(" ") and not line.startswith("\t"):
            in_section = line.rstrip() == section + ":"
            continue
        if in_section:
            m = re.match(rf"^\s+{re.escape(key)}:\s*(.*)$", line)
            if m:
                v = m.group(1).strip()
                if len(v) >= 2 and v[0] == '"' and v[-1] == '"':
                    v = v[1:-1]
                return v
    return ""


def patch_yaml_field(text: str, section: str, key: str, value: str,
                     quote: bool = True) -> str:
    """Replace the single `key:` line inside top-level `section:`.

    Line-based (no YAML round-trip) so every other byte of the file is
    preserved. Raises ProfileError if the section or key is missing.
    """
    val = f'"{value}"' if quote else value
    out = []
    in_section = False
    replaced = False
    for line in text.splitlines(keepends=True):
        if not line.startswith(" ") and not line.startswith("\t"):
            in_section = line.rstrip("\n").rstrip() == section + ":"
        if in_section and not replaced \
                and re.match(rf"^\s+{re.escape(key)}\s*:", line):
            indent = re.match(r"^[ \t]*", line).group(0)
            newline = "\n" if line.endswith("\n") else ""
            out.append(f"{indent}{key}: {val}{newline}")
            replaced = True
            continue
        out.append(line)
    if not replaced:
        raise ProfileError(f"simbridge.yaml: key {section}.{key} not found")
    return "".join(out)


# ---------------------------------------------------------------------------
# Live-state readers (capture / status / probe)
# ---------------------------------------------------------------------------

def parse_dongle_conf(text: str) -> dict:
    """Parse [section] name + audio/data/alsadev from a dongle.conf text."""
    section = ""
    dev = {"audio": "", "data": "", "alsadev": ""}
    for line in text.splitlines():
        line = line.strip()
        m = re.match(r"^\[(.+)\]$", line)
        if m:
            section = m.group(1)
            continue
        if section and section != "general":
            m = re.match(r"^(audio|data|alsadev)\s*=\s*(\S+)", line)
            if m:
                dev[m.group(1)] = m.group(2)
    return {"section": section, **dev}


def parse_udev_all(text: str) -> dict:
    """Parse `udevadm info -q all` output into a dict (last value wins).

    Property lines carry a one-letter record prefix (properties are
    'E: KEY=value'; also 'P:'/'M:'/'R:'/'U:' lines without '=') — the
    prefix is optional so plain KEY=value dumps parse too.
    """
    out = {}
    for line in text.splitlines():
        m = re.match(r"^(?:[A-Z]: )?([A-Za-z0-9_]+)=(.*)$", line)
        if m:
            out[m.group(1)] = m.group(2).strip('"')
    return out


def _udev_meta(dev: str) -> dict:
    """udevadm metadata for device *dev*.

    Symlinks are resolved first: `udevadm info -n` given a symlink NAME
    (e.g. /dev/dongle_if1) returns a reduced property set (no
    ID_USB_INTERFACE_NUM / ID_MODEL_ID) on this system, while the
    resolved device path (/dev/ttyUSB1) returns the full set.
    """
    dev_real = os.path.realpath(dev)
    r = run(f"udevadm info -q all -n {shlex.quote(dev_real)} 2>/dev/null")
    return parse_udev_all(r.stdout)


def _capture_from_live() -> dict:
    """Build a profile dict from the live state (modem must be plugged in)."""
    ps = paths()
    if not ps["dongle_conf"].is_file():
        raise ProfileError(f"no {ps['dongle_conf']} — nothing to capture")
    dc = parse_dongle_conf(ps["dongle_conf"].read_text(errors="replace"))
    if not dc["section"] or not dc["data"] or \
            (not dc["alsadev"] and not dc["audio"]):
        raise ProfileError(
            f"dongle.conf: cannot find [section] with data= and a voice "
            f"port (audio= or alsadev= for UAC) "
            f"(got section={dc['section']!r})")

    yaml_text = ""
    if ps["config_yaml"].is_file():
        yaml_text = ps["config_yaml"].read_text(errors="replace")
    dongle_name = _yaml_field(yaml_text, "asterisk", "dongle") or dc["section"]
    modem_model = _yaml_field(yaml_text, "sim", "modem_model")
    sim_phone = _yaml_field(yaml_text, "sim", "phone")

    # vid:pid + interface map from udev (authoritative) with an lsusb-line
    # fallback for the vid:pid only.
    vid = pid = ""
    udev_map = []
    r = run("ls -1 /dev/dongle_if* 2>/dev/null")
    for dev in r.stdout.split():
        meta = _udev_meta(dev)
        iface = meta.get("ID_USB_INTERFACE_NUM", "")
        if meta.get("ID_VENDOR_ID"):
            vid = meta["ID_VENDOR_ID"]
        if meta.get("ID_MODEL_ID"):
            pid = meta["ID_MODEL_ID"]
        if re.fullmatch(r"\d{2}", iface):
            udev_map.append({"iface": iface, "symlink": Path(dev).name})
    if not (vid and pid) and modem_model:
        m = re.search(r"\bID\s+([0-9a-fA-F]{4}):([0-9a-fA-F]{4})", modem_model)
        if m:
            vid, pid = m.group(1), m.group(2)
    udev_map.sort(key=lambda e: e["iface"])

    prof = {
        "name": dongle_name,
        "modem_model": modem_model,
        "vid_pid": f"{vid}:{pid}" if vid and pid else "",
        "dongle_name": dongle_name,
        "audio_device": "" if dc["alsadev"] else dc["audio"],
        "data_device": dc["data"],
        "sim_phone": sim_phone,
        "udev": udev_map,
        "verified": True,   # captured from a currently working live state
        "notes": "captured from live state by modem_profile.py capture",
    }
    if dc["alsadev"]:
        prof["alsadev"] = dc["alsadev"]
    return prof


# termios speed slots hold speed INDICES (termios.B115200 == 15 on Linux),
# not baud-rate numbers — mapping from the rate to the constant name.
_AT_SPEEDS = {9600: "B9600", 19200: "B19200", 38400: "B38400",
              57600: "B57600", 115200: "B115200"}


def at_query(dev: str, at_cmd: str, baud: int = 115200,
             timeout: float = 2.5) -> str:
    """Send one AT command to *dev* (raw termios, stdlib only).

    Returns the response body with echo and the final OK/ERROR line
    stripped; "" on any failure (unopenable port, no answer).
    """
    import fcntl
    import termios
    import tty

    try:
        fd = os.open(dev, os.O_RDWR | os.O_NOCTTY)
    except OSError:
        return ""
    orig = None
    try:
        orig = termios.tcgetattr(fd)   # kept for restore in finally
        tty.setraw(fd)
        attrs = termios.tcgetattr(fd)  # raw-mode attrs, current speed
        # tcgetattr list layout: [iflag, oflag, cflag, lflag, ispeed,
        # ospeed, cc] — the speed slots hold speed INDICES (termios.B115200
        # == 15 on Linux), not baud-rate numbers. This RHEL Python build's
        # termios exposes no cfsetspeed/cfsetispeed, so set the slots
        # directly.
        speed = getattr(termios, _AT_SPEEDS.get(baud, "B115200"))
        attrs[4] = speed
        attrs[5] = speed
        termios.tcsetattr(fd, termios.TCSANOW, attrs)
        # select() is the ONLY arbiter: a blocking os.read() on a serial
        # tty can sleep forever after select() reports the fd ready with
        # nothing pending (observed live on the EC25 diag port, kernel
        # stuck in n_tty_read). O_NONBLOCK turns that into EAGAIN.
        flags = fcntl.fcntl(fd, fcntl.F_GETFL)
        fcntl.fcntl(fd, fcntl.F_SETFL, flags | os.O_NONBLOCK)
        try:
            termios.tcflush(fd, termios.TCIFLUSH)
        except termios.error:
            pass
        os.write(fd, (at_cmd + "\r").encode())
        chunks = []
        deadline = time.time() + timeout
        while time.time() < deadline:
            rlist, _, _ = select.select([fd], [], [], 0.25)
            if not rlist:
                continue
            try:
                chunk = os.read(fd, 1024)
            except BlockingIOError:
                continue           # select race: no data yet, keep polling
            except OSError:
                break
            if not chunk:
                break
            chunks.append(chunk)
            if b"OK" in chunk or b"ERROR" in chunk:
                break  # terminal response line received
        resp = b"".join(chunks).decode("utf-8", "replace")
        lines = [ln.strip() for ln in resp.splitlines() if ln.strip()]
        body = [ln for ln in lines if ln not in ("OK", "ERROR")
                and ln != at_cmd.replace("\r", "")]
        return "\n".join(body)
    finally:
        if orig is not None:
            try:
                termios.tcsetattr(fd, termios.TCSANOW, orig)
            except (termios.error, OSError):
                pass
        os.close(fd)


def _probe_devices() -> list:
    """Enumerate ttyUSB/ttyACM ports with their udev metadata."""
    r = run("ls -1 /dev/ttyUSB* /dev/ttyACM* 2>/dev/null")
    devs = []
    for dev in r.stdout.split():
        meta = _udev_meta(dev)
        devs.append({
            "dev": dev,
            "vid": meta.get("ID_VENDOR_ID", ""),
            "pid": meta.get("ID_MODEL_ID", ""),
            "iface": meta.get("ID_USB_INTERFACE_NUM", ""),
            "model": meta.get("ID_MODEL", ""),
        })
    return devs


# ---------------------------------------------------------------------------
# Subcommands
# ---------------------------------------------------------------------------

def cmd_list(_args) -> int:
    ps = paths()
    if not ps["profiles_dir"].is_dir():
        print(f"(no profiles — directory {ps['profiles_dir']} does not exist)")
        return 0
    active = read_active()
    names = sorted(p.stem for p in ps["profiles_dir"].glob("*.yaml"))
    if not names:
        print("(no profiles)")
        return 0
    for n in names:
        p = {}
        try:
            p = load_profile(ps["profiles_dir"] / f"{n}.yaml")
            verified = "verified" if p["verified"] else "UNVERIFIED"
        except ProfileError as e:
            verified = f"INVALID ({e})"
        mark = "ACTIVE" if n == active else "      "
        print(f"[{mark}] {n:20s} {verified:12s} "
              f"vid:pid={p.get('vid_pid') or '-'}  "
              f"dongle={p.get('dongle_name', '-')}")
    return 0


def cmd_show(args) -> int:
    ps = paths()
    name = args.name or read_active()
    if not name:
        raise ProfileError("no profile name given and no active_modem pointer")
    path = profile_path(name)
    if not path.is_file():
        raise ProfileError(f"no such profile: {name}")
    sys.stdout.write(path.read_text())
    return 0


def cmd_status(_args) -> int:
    ps = paths()
    active = read_active()
    prof = None
    print(f"Active profile : {active or '<none>'}")
    if active:
        path = profile_path(active)
        if path.is_file():
            prof = load_profile(path)
            print(f"  modem        : {prof['modem_model']}")
            print(f"  vid:pid      : {prof.get('vid_pid') or '-'}")
            print(f"  channel      : {prof['dongle_name']}  "
                  f"(audio={prof['audio_device'] or '-'} "
                  f"data={prof['data_device']})")
            if prof.get("alsadev"):
                print(f"  UAC voice    : alsadev={prof['alsadev']}")
            print(f"  verified     : {prof['verified']}")

    r = run("lsusb 2>/dev/null")
    kw = re.compile(r"huawei|quectel|dacom|simcom|telit|wavecom|gsm|modem", re.I)
    print("Plugged in USB :")
    found = False
    for line in r.stdout.splitlines():
        if not kw.search(line):
            continue
        found = True
        m = re.search(r"\b([0-9a-fA-F]{4}):([0-9a-fA-F]{4})\b", line)
        vidpid = f"{m.group(1).lower()}:{m.group(2).lower()}" if m else "?"
        mark = ""
        if prof and prof.get("vid_pid"):
            mark = "  MATCH" if vidpid == prof["vid_pid"].lower() else \
                "  MISMATCH (profile says " + prof["vid_pid"] + ")"
        print(f"  {vidpid}  {mark}  {line.strip()}")
    if not found:
        print("  (no modem keyword match in lsusb — is the modem plugged in?)")

    r = run("asterisk -rx 'dongle show devices' 2>&1", timeout=15)
    print("dongle devices :")
    for line in (r.stdout or r.stderr).splitlines():
        print(f"  {line}")
    r = run("systemctl is-active simbridge-agent 2>&1")
    print(f"simbridge-agent: {r.stdout.strip()}")

    # ModemManager must not manage the dongle (chan_dongle owns the
    # ports). The rendered ID_MM_DEVICE_IGNORE tags block FRESH
    # enumeration; if MM adopted the dongle before the rule existed
    # (e.g. it was plugged in earlier), a udev change event will NOT
    # make it drop the device — a one-time service restart will.
    mm = run("systemctl is-active ModemManager 2>&1")
    if mm.stdout.strip() == "active":
        r = run("mmcli -L 2>/dev/null")
        modems = [l for l in r.stdout.splitlines() if l.startswith("/")]
        if modems:
            print("ModemManager   : ACTIVE — managing modems:")
            for l in modems:
                print(f"  {l}")
            print("  (the dongle must not be among them; if the channel "
                  "is stuck 'Not connec' with EBUSY in the Asterisk "
                  "log, run: systemctl restart ModemManager)")
        else:
            print("ModemManager   : active, no managed modems")
    return 0


def cmd_new(args) -> int:
    path = profile_path(args.name)
    if path.exists() and not args.force:
        raise ProfileError(f"profile already exists: {path} (use --force)")
    udev = []
    if args.vid_pid:
        for iface in ("00", "01", "02"):
            udev.append({"iface": iface, "symlink": f"dongle_if{int(iface)}"})
    p = {
        "name": args.name,
        "modem_model": args.modem_model or "",
        "vid_pid": args.vid_pid or "",
        "dongle_name": args.dongle_name or "gsm",
        "audio_device": args.audio or "/dev/dongle_if1",
        "data_device": args.data or "/dev/dongle_if2",
        "sim_phone": args.sim_phone or "",
        "udev": udev,
        "verified": False,
        "notes": "template — complete with probe --commit or capture; "
                 "verified stays false until a live E2E test passes",
    }
    write_profile(p)
    print(f"Created unverified template: {path}")
    print("  Complete it (probe --commit / edit) then: "
          f"modem_profile.py use {args.name} --force")
    return 0


def cmd_capture(args) -> int:
    path = profile_path(args.name)
    if path.exists() and not args.force:
        raise ProfileError(f"profile already exists: {path} (use --force)")
    p = _capture_from_live()
    p["name"] = args.name
    write_profile(p)
    print(f"Captured live state into: {path}")
    print(render_profile(p), end="")
    print("Profile is marked verified (it reflects the working live state).")
    if read_active() != args.name:
        print(f"To make it active: modem_profile.py use {args.name}")
    return 0


# Canonical EC2x (0x2C7C) USB interface numbering, per the Quectel
# "USB Interface Descriptor" doc (Table 2). cmd_probe trusts this map only
# when the empirical AT port (AT+CGMM) sits at its canonical slot.
_EC2X_IFACE_ROLES = {"00": "dm", "01": "nmea", "02": "at", "03": "modem"}


def interpret_usbcfg(usbcfg: str) -> str:
    """Decode an AT+QCFG="USBCFG" answer and state the voice path.

    EC2x numeric format (Quectel QCFG manual 9.2, 0x2C7C PIDs):
      +QCFG: "usbcfg",<vid>,<pid>,<diag>,<nmea>,<at_port>,<modem>,
             <rmnet>,<adb>,<uac>
    — seven 0/1 port flags after vid/pid. Older firmwares answer a named
    mode string instead (EC20-style "QMI,ECM,...,AUD,...,UAC=0"); a
    keyword fallback covers that.

    Voice options per the Quectel EC2x "Voice Over USB and UAC" app note:
      - serial PCM via the NMEA port (AT+QPCMV option 0) — usable via the
        serial audio tty; needs nmea=1 and the NMEA port free of GNSS
        output;
      - UAC USB sound card (uac=1) — usable via the alsadev setting
        (chan_dongle patch 0003): voice rides a virtual USB sound card,
        located at probe time from /proc/asound/cards.
    Returns 'uac', 'serial', or 'none' (the usable voice path).
    """
    parts = [f.strip() for f in
             usbcfg.split('"')[-1].strip().strip(',').split(',')]
    if (len(parts) == 9
            and all(re.fullmatch(r"0x[0-9A-Fa-f]+", f) for f in parts[:2])
            and all(re.fullmatch(r"[01]", f) for f in parts[2:])):
        diag, nmea, at_p, modem, net, adb, uac = (int(f) for f in parts[2:])
        print(f"  ports          : diag={diag} nmea={nmea} at={at_p} "
              f"modem={modem} net={net} adb={adb} uac={uac}")
        if uac:
            print("  voice          : UAC (USB sound card) — supported by "
                  "this chan_dongle build (patch 0003); probe locates the "
                  "card, record it in the profile alsadev")
            return "uac"
        elif nmea:
            print("  voice          : SERIAL PCM via the NMEA port "
                  "(AT+QPCMV option 0) — usable by this chan_dongle "
                  "build; the NMEA port must be free of GNSS output")
            return "serial"
        else:
            print("  voice          : NO voice port exposed (nmea=0, uac=0) "
                  '— change the mode (AT+QCFG="USBCFG",...) and re-probe')
            return "none"
    # legacy named mode string (EC20-style)
    serial_audio = "Audio" in usbcfg or "AUD" in usbcfg
    uac = "UAC=1" in usbcfg or (
        re.findall(r'"([^"]*)"', usbcfg)
        and "UAC" in re.findall(r'"([^"]*)"', usbcfg)[-1])
    if serial_audio:
        print("  voice          : SERIAL audio port present — "
              "chan_dongle can use it")
        return "serial"
    elif uac:
        print("  voice          : UAC (USB sound card) only — supported "
              "by this chan_dongle build (patch 0003); record the card "
              "in the profile alsadev")
        return "uac"
    else:
        print("  voice          : no voice port in this USBCFG mode — "
              "change mode and re-probe")
        return "none"


def _find_uac_card(hint: str = "") -> str:
    """Locate the modem's UAC sound card among the ALSA cards.

    /proc/asound/cards lists 'N [SHORT]: Bus - long name' (the long
    name may continue on the next indented line). The first USB-Audio
    card whose name matches *hint* (case-insensitive substring; empty
    hint = any USB-Audio card) that has BOTH a capture and a playback
    PCM0 wins. The card name changes across USB re-enumerations, so it
    is always read from the live state, never hardcoded.
    Returns 'hw:CARD=<short>,DEV=0' or ''.
    """
    r = run("cat /proc/asound/cards 2>/dev/null")
    cards = []
    lines = (r.stdout or "").splitlines()
    i = 0
    while i < len(lines):
        # the short name is whitespace-padded inside the brackets:
        # ' 3 [EC25EUX        ]: USB-Audio - EC25-EUX'
        m = re.match(r"^\s*(\d+)\s+\[([^\]]+)\]\s*:\s*(\S+)\s*-\s*(.*)$",
                     lines[i])
        if m:
            desc = m.group(4)
            if i + 1 < len(lines) and lines[i + 1][:1] == " ":
                desc += " " + lines[i + 1].strip()
                i += 1
            cards.append((m.group(1), m.group(2).strip(),
                          m.group(3), desc))
        i += 1
    for idx, short, bus, desc in cards:
        if bus != "USB-Audio":
            continue
        if hint and hint.lower() not in f"{short} {desc}".lower():
            continue
        card = f"/proc/asound/card{idx}"
        if run(f"test -e {card}/pcm0c -a -e {card}/pcm0p").returncode == 0:
            return f"hw:CARD={short},DEV=0"
    return ""


def cmd_probe(args) -> int:
    devs = _probe_devices()
    if not devs:
        raise ProfileError("no ttyUSB/ttyACM devices found — "
                           "is the modem plugged in?")
    # Warn if Asterisk is actually CONNECTED to a dongle (State Free/Busy) —
    # then probe would interleave with chan_dongle's own AT traffic. A
    # channel that is "Not connec"/"OFFLINE" holds no port.
    r = run("asterisk -rx 'dongle show devices' 2>&1", timeout=15)
    if r.returncode == 0 and re.search(r"\b(Free|Busy)\b", r.stdout or ""):
        print("[warn] a dongle is CONNECTED in Asterisk — for a clean "
              "probe stop it first: systemctl stop asterisk")

    print("Discovered ports:")
    for d in devs:
        print(f"  {d['dev']:16s} vid:pid={d['vid']}:{d['pid']} "
              f"iface={d['iface'] or '-'}  {d['model'][:50]}")

    # AT+CGMM is the decisive probe: only the module's AT port answers it
    # (audio/data TTYs have no modem controller behind them).
    at_dev, cgmm = None, ""
    for d in devs:
        cgmm_try = at_query(d["dev"], "AT+CGMM")
        if cgmm_try:
            at_dev, cgmm = d["dev"], cgmm_try
            break
    print(f"AT port        : {at_dev or 'NOT FOUND'}"
          + (f"  (AT+CGMM -> {cgmm})" if cgmm else ""))

    voice_mode = ""
    alsadev_guess = ""
    if at_dev:
        usbcfg = at_query(at_dev, 'AT+QCFG="USBCFG"')
        if usbcfg:
            print(f"USBCFG         : {usbcfg}")
            voice_mode = interpret_usbcfg(usbcfg)
        else:
            print("USBCFG         : no answer (not a Quectel module or "
                  "unsupported)")

        # Serial voice (Voice over USB): per the Quectel EC2x app note the
        # PCM stream rides the NMEA port (AT+QPCMV option 0), so QPCMV must
        # be supported and the NMEA port must be free of GNSS output.
        qpcmv = at_query(at_dev, "AT+QPCMV?")
        if qpcmv:
            if voice_mode == "uac":
                print(f"QPCMV          : {qpcmv}  — the driver arms "
                      "AT+QPCMV=1,2 per call (UAC transport)")
            else:
                print(f"QPCMV          : {qpcmv}  — serial voice supported "
                      "(chan_dongle arms it per call)")
        else:
            print("QPCMV          : no answer — serial voice NOT available "
                  "on this firmware")
        gps_out = at_query(at_dev, 'AT+QGPSCFG="outport"')
        if gps_out:
            print(f"GPS outport    : {gps_out}")
            # Firmware answers the value with or without quotes
            # (live EC25: '+QGPSCFG: "outport",usbnmea') — match both.
            if re.search(r"\busbnmea\b", gps_out):
                print("  [warn] GNSS output is ON the USB NMEA port — before "
                      "serial voice set AT+QGPSCFG=\"outport\",\"none\"")

        # UAC voice: the audio path is a virtual USB sound card, not a tty.
        # The card is only guaranteed to exist after a USB re-enumeration
        # with USBCFG uac=1, so it is located live, never hardcoded.
        if voice_mode == "uac":
            alsadev_guess = _find_uac_card(cgmm)
            if alsadev_guess:
                print(f"UAC card       : {alsadev_guess}  (record it as "
                      "alsadev in the profile)")
            else:
                print("UAC card       : NOT FOUND among the ALSA cards — "
                      "check /proc/asound/cards (the card appears only "
                      "after a USB re-enumeration with USBCFG uac=1)")

    # Guess: data = AT port (empirical, via AT+CGMM). Audio = the voice
    # port: for EC2x (0x2C7C) the Quectel USB interface descriptor doc
    # fixes the numbering (0=DM, 1=NMEA, 2=AT, 3=Modem) and serial voice
    # PCM rides the NMEA port — when the empirical AT port sits at its
    # canonical slot the map is trusted and audio = the NMEA port.
    # Everything else falls back to the first non-AT port that is not the
    # EC2x DM/diag slot (still UNVERIFIED — confirm before use).
    data_guess = at_dev or ""
    audio_guess = ""
    at_entry = next((d for d in devs if d["dev"] == at_dev), None)
    if (at_entry is not None and at_entry["vid"].lower() == "2c7c"
            and _EC2X_IFACE_ROLES.get(at_entry["iface"]) == "at"):
        audio_guess = next((d["dev"] for d in devs
                            if _EC2X_IFACE_ROLES.get(d["iface"]) == "nmea"),
                           "")
    if not audio_guess:
        for d in devs:
            if (d["dev"] != at_dev and re.fullmatch(r"\d{2}", d["iface"])
                    and not (d["vid"].lower() == "2c7c"
                             and _EC2X_IFACE_ROLES.get(d["iface"]) == "dm")):
                audio_guess = d["dev"]
                break
    if alsadev_guess:
        print(f"Guess          : data={data_guess or '?'}  "
              f"alsadev={alsadev_guess}   (UAC voice — UNVERIFIED, "
              "confirm before use)")
    else:
        print(f"Guess          : data={data_guess or '?'}  "
              f"audio={audio_guess or '?'}   (UNVERIFIED — confirm before use)")

    if not args.commit:
        print("\nReview the mapping, then:")
        voice = (f" --alsadev {shlex.quote(alsadev_guess)}"
                 if alsadev_guess
                 else f" --audio {shlex.quote(audio_guess)}")
        print(f"  modem_profile.py probe --commit <name> "
              f"--data {shlex.quote(data_guess)}{voice}")
        return 0

    # --commit: write/extend the profile from the findings.
    vid = pid = ""
    for d in devs:
        if d["vid"] and d["pid"]:
            vid, pid = d["vid"], d["pid"]
            break
    data_dev = args.data or data_guess
    audio_dev = args.audio or audio_guess
    # UAC voice: an explicit --alsadev wins over the live card detection.
    # In UAC mode there is no PCM on the serial ports — the serial audio
    # guess is not a voice path, alsadev is the only one.
    alsadev = getattr(args, "alsadev", "") or \
        (alsadev_guess if voice_mode == "uac" else "")
    if voice_mode == "uac":
        audio_dev = ""
    if not data_dev:
        raise ProfileError("probe --commit: could not determine the data "
                           "port — pass --data explicitly")
    if not alsadev and not audio_dev:
        raise ProfileError("probe --commit: could not determine the voice "
                           "path — pass --audio (serial PCM port) or "
                           "--alsadev (UAC card) explicitly")
    # Audio via the stable udev symlink (dongle_if<iface>), data via symlink too.
    iface_of = {d["dev"]: d["iface"] for d in devs}
    udev_map = []
    for d in sorted(devs, key=lambda x: (x["iface"] or "99")):
        if re.fullmatch(r"\d{2}", d["iface"]):
            udev_map.append({"iface": d["iface"],
                             "symlink": f"dongle_if{int(d['iface'])}"})
    def _as_symlink(dev):
        iface = iface_of.get(dev, "")
        # dongle_if<iface-as-integer> — the live convention (iface "01"
        # is dongle_if1, not dongle_if01)
        return f"/dev/dongle_if{int(iface)}" if iface else dev

    ps = paths()
    name = args.commit
    existing = profile_path(name)
    p = load_profile(existing) if existing.is_file() else {
        "name": name, "modem_model": "", "vid_pid": "", "dongle_name": "gsm",
        "audio_device": "", "data_device": "", "sim_phone": "",
        "udev": [], "verified": False, "notes": "",
    }
    p["modem_model"] = (next((d["model"] for d in devs if d["model"]), "")
                        or p["modem_model"])
    if vid and pid:
        p["vid_pid"] = f"{vid}:{pid}"
    if alsadev:
        p["audio_device"] = ""
        p["alsadev"] = alsadev
    else:
        p["audio_device"] = _as_symlink(audio_dev)
        p.pop("alsadev", None)
    p["data_device"] = _as_symlink(data_dev)
    if udev_map:
        p["udev"] = udev_map
    p["verified"] = False
    p["notes"] = ("probe: AT+CGMM answered on data port; port mapping is a "
                  "GUESS until a live E2E test passes — see "
                  "AT/USBCFG output in the session log")
    write_profile(p)
    print(f"\nProfile written: {profile_path(name)} (verified: false)")
    if alsadev:
        print(f"  UAC voice  : alsadev={alsadev} (audio= not used; the "
              "asterisk user must be in the 'audio' group)")
    print("Verify with a real SMS/call, then: "
          f"modem_profile.py use {name} --force")
    return 0


def cmd_init(args) -> int:
    """Fresh-install path (called by deploy/install.py): create the profile
    from installer answers and render the artifacts. No restarts — the
    installer starts services itself."""
    path = profile_path(args.name)
    if path.exists() and not args.force:
        raise ProfileError(f"profile already exists: {path} (use --force)")
    udev = []
    if args.vid_pid:
        for iface in (i.strip() for i in (args.interfaces or "00,01,02").split(",")):
            if re.fullmatch(r"\d{2}", iface):
                udev.append({"iface": iface, "symlink": f"dongle_if{int(iface)}"})
    p = {
        "name": args.name,
        "modem_model": args.modem_model or "",
        "vid_pid": args.vid_pid or "",
        "dongle_name": args.dongle_name or "gsm",
        "audio_device": args.audio or "/dev/dongle_if1",
        "data_device": args.data or "/dev/dongle_if2",
        "sim_phone": args.sim_phone or "",
        "udev": udev,
        "verified": False,
        "notes": "created by install.py (fresh install) — refine with "
                 "probe/capture after the first live test",
    }
    write_profile(p)
    write_active(args.name)
    apply_artifacts(p, backup_old=True)
    print(f"Profile {args.name} created and active; artifacts rendered.")
    return 0


def cmd_apply(args) -> int:
    path = profile_path(args.name)
    if not path.is_file():
        raise ProfileError(f"no such profile: {args.name}")
    p = load_profile(path)
    res = apply_artifacts(p, backup_old=True)
    print(f"Artifacts rendered for {args.name}:")
    print(f"  udev      : {res['udev'] or '(unchanged or not rendered)'}")
    print(f"  dongle    : {res['dongle_conf']}")
    for b in res["backups"]:
        print(f"  backup    : {b}")
    print("No services were restarted (use `use` for a full switch).")
    return 0


def _switch(name: str, force: bool) -> int:
    ps = paths()
    path = profile_path(name)
    if not path.is_file():
        raise ProfileError(f"no such profile: {name}")
    p = load_profile(path)
    if not p["verified"] and not force:
        raise ProfileError(
            f"profile {name} is NOT verified (verified: false).\n"
            f"  Run a live end-to-end check first (SMS/call) and set "
            f"verified: true — or re-run with --force to acknowledge the\n"
            f"  unverified state explicitly.")

    prev = read_active()
    udev_text = None
    if p.get("vid_pid") and p.get("udev"):
        udev_text = render_udev_rules(p)
    dtext = render_dongle_conf(p)

    yaml_text = ps["config_yaml"].read_text() if ps["config_yaml"].is_file() \
        else ""
    old_dongle = _yaml_field(yaml_text, "asterisk", "dongle") if yaml_text \
        else ""
    new_yaml = yaml_text
    if yaml_text:
        new_yaml = patch_yaml_field(yaml_text, "asterisk", "dongle",
                                    p["dongle_name"], quote=False)
        new_yaml = patch_yaml_field(new_yaml, "sim", "modem_model",
                                    p["modem_model"])

    in_sync = (
        prev == name
        and (udev_text is None
             or (ps["udev_rule"].is_file()
                 and ps["udev_rule"].read_text() == udev_text))
        and ps["dongle_conf"].is_file()
        and ps["dongle_conf"].read_text() == dtext
        and new_yaml == yaml_text
    )
    if in_sync:
        print(f"Profile {name} is already active and all artifacts are in "
              f"sync — nothing to do (no restarts).")
        return 0

    print(f"Switching modem profile: {prev or '<none>'} -> {name}")
    res = apply_artifacts(p, backup_old=True)
    if yaml_text:
        _write_atomic(ps["config_yaml"], new_yaml, 0o644)
        print(f"  Updated {ps['config_yaml']}: "
              f"asterisk.dongle={p['dongle_name']}, sim.modem_model")
    else:
        print(f"  [warn] {ps['config_yaml']} not found — skipped yaml update")
    write_active(name)
    print(f"  Active pointer: {ps['active']} -> {name}")

    gen = str(GENERATOR)
    r = run(f"{sys.executable} {shlex.quote(gen)} {shlex.quote(str(ps['config_yaml']))} "
            f"-o {shlex.quote(str(ps['globals']))}", timeout=60)
    if r.returncode == 0:
        print(f"  Regenerated {ps['globals']} (existing generator)")
    else:
        print(f"  [warn] globals regeneration failed: "
              f"{(r.stderr or r.stdout).strip()[:300]}")

    print("Restarting services...")
    run("systemctl restart asterisk")
    print("  asterisk restarted")
    if old_dongle and old_dongle != p["dongle_name"]:
        run("systemctl restart simbridge-agent")
        print(f"  simbridge-agent restarted (channel name "
              f"{old_dongle} -> {p['dongle_name']})")
    else:
        print("  simbridge-agent NOT restarted (channel name unchanged)")

    # Verify — retry a few times while Asterisk comes up.
    ok = False
    out = ""
    for _ in range(4):
        time.sleep(3)
        r = run("asterisk -rx 'dongle show devices' 2>&1", timeout=15)
        out = r.stdout
        ok = r.returncode == 0 and p["dongle_name"] in out
        if ok:
            break
    ra = run("systemctl is-active simbridge-agent 2>&1")
    agent_ok = ra.stdout.strip() == "active"

    print("\nVerification:")
    for line in (out or "").splitlines():
        print(f"  {line}")
    print(f"  simbridge-agent: {ra.stdout.strip()}")

    if ok and agent_ok:
        print(f"\nSUCCESS — profile {name} is active.")
        print("Remaining step (Rule 2/3): a live end-to-end SMS/call on this "
              "modem,\nthen set verified: true in the profile.")
        return 0

    print("\nFAILED — the modem did not register or the agent is down.")
    print("Rollback: put the previous modem back, then run:")
    if prev:
        print(f"  {sys.executable} {Path(__file__).resolve()} use {prev}")
    else:
        print("  (no previous profile was recorded)")
    print("Backups made by this run:")
    for b in res["backups"]:
        print(f"  {b}")
    return 1


def cmd_use(args) -> int:
    return _switch(args.name, args.force)


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(
        prog="modem_profile.py",
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest="cmd", required=True)

    sub.add_parser("list", help="show all profiles").set_defaults(fn=cmd_list)

    sp = sub.add_parser("show", help="print a profile (default: active)")
    sp.add_argument("name", nargs="?", default="")
    sp.set_defaults(fn=cmd_show)

    sub.add_parser("status", help="active profile vs plugged-in device").set_defaults(fn=cmd_status)

    sp = sub.add_parser("new", help="create an unverified template profile")
    sp.add_argument("name")
    sp.add_argument("--modem-model", default="")
    sp.add_argument("--vid-pid", default="")
    sp.add_argument("--dongle-name", default="")
    sp.add_argument("--audio", default="")
    sp.add_argument("--data", default="")
    sp.add_argument("--sim-phone", default="")
    sp.add_argument("--force", action="store_true")
    sp.set_defaults(fn=cmd_new)

    sp = sub.add_parser("capture", help="create a verified profile from the "
                                        "live state")
    sp.add_argument("name")
    sp.add_argument("--force", action="store_true")
    sp.set_defaults(fn=cmd_capture)

    sp = sub.add_parser("probe", help="inspect the plugged-in modem; "
                                      "--commit writes the findings")
    sp.add_argument("--commit", default="", metavar="NAME")
    sp.add_argument("--audio", default="",
                    help="serial PCM audio tty (default: guessed)")
    sp.add_argument("--data", default="",
                    help="data tty (default: the AT port, via AT+CGMM)")
    sp.add_argument("--alsadev", default="",
                    help="UAC ALSA card, e.g. hw:CARD=EC25EUX,DEV=0 "
                         "(default: auto-detected from /proc/asound/cards "
                         "when USBCFG has uac=1)")
    sp.set_defaults(fn=cmd_probe)

    sp = sub.add_parser("init", help="(installer) create profile from "
                                     "answers + render artifacts")
    sp.add_argument("name")
    sp.add_argument("--modem-model", default="")
    sp.add_argument("--vid-pid", default="")
    sp.add_argument("--dongle-name", default="")
    sp.add_argument("--audio", default="")
    sp.add_argument("--data", default="")
    sp.add_argument("--sim-phone", default="")
    sp.add_argument("--interfaces", default="00,01,02")
    sp.add_argument("--force", action="store_true")
    sp.set_defaults(fn=cmd_init)

    sp = sub.add_parser("apply", help="re-render udev + dongle.conf for a "
                                      "profile (no restarts)")
    sp.add_argument("name")
    sp.set_defaults(fn=cmd_apply)

    sp = sub.add_parser("use", help="switch to a profile (full flow)")
    sp.add_argument("name")
    sp.add_argument("--force", action="store_true",
                    help="allow an unverified profile")
    sp.set_defaults(fn=cmd_use)

    args = ap.parse_args(argv)
    try:
        return args.fn(args)
    except ProfileError as e:
        print(f"ERROR: {e}", file=sys.stderr)
        return 1
    except KeyboardInterrupt:
        return 130


if __name__ == "__main__":
    sys.exit(main())
